### ISSUE TITLE
Problem when i listen to handleOnChange inside useEffect

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#107]
@targos @stropitek @lpatiny 

https://github.com/cheminfo/nmr-displayer/blob/dd5326c3d4dc6a122a98f30fd9b0244741171234/src/component/elements/toggle/ToggleButtonGroup.js#L35-L37

**Comment by targos** [comment]
we don't know what you are trying to achieve. the ToggleButtonGroup component seems to have a useless state (the array is always empty). Please explain your problem.

**Comment by hamed-musallam** [comment]
> we don't know what you are trying to achieve. the ToggleButtonGroup component seems to have a useless state (the array is always empty). Please explain your problem.

Which array do you mean that it always empty?  ToggleButtonGroup responsible to manage selected options, only allow one option I mean one toggleButton is active at a time.
