### ISSUE TITLE
Problem when i listen to onBrush inside useEffect

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#108]
@lpatiny @targos @stropitek 
when i add a Brush inside [ ] in useEffect beside state the component rerender continually.

https://github.com/cheminfo/nmr-displayer/blob/dd5326c3d4dc6a122a98f30fd9b0244741171234/src/component/EventsTrackers/BrushTracker.js#L110-L114

**Comment by targos** [comment]
You need to make sure your `onBrush` function is not recreated on every render [here](https://github.com/cheminfo/nmr-displayer/blob/5371d921bb3898d16133fce2bd3aac76418b2863/src/component/NMRDisplayer.jsx#L144). You can call `useCallback` for that.

**Comment by hamed-musallam** [comment]
> `useCallback`



> You need to make sure your `onBrush` function is not recreated on every render [here](https://github.com/cheminfo/nmr-displayer/blob/5371d921bb3898d16133fce2bd3aac76418b2863/src/component/NMRDisplayer.jsx#L144). You can call `useCallback` for that.


i try that option but you can't use useCallback inside useSize, so What to do?

**Comment by targos** [comment]
Are you sure you need to create those callbacks inside of the `useSize` hook? it looks to me that you could instead do that just before `useSize` is called and you would be able to use `useCallback` here.

**Comment by hamed-musallam** [comment]
> Are you sure you need to create those callbacks inside of the `useSize` hook? it looks to me that you could instead do that just before `useSize` is called and you would be able to use `use callback` here.

I used useCallback for onBrush event handler and I add it outside the useSize, but we have another problem if you use zoom brush first and used it to zoom to specific area and then select another tool " not matter if it's peak picking or integral tool "  it will Trigger the onBrush, can you check the code I push the last version of the code at GitHub

**Comment by hamed-musallam** [comment]
can you or Daniel  check the code for this problem?

**Comment by stropitek** [comment]
@hamed-musallam 

indeed that is a bug with the BrushTracker component. I'm looking into it

**Comment by stropitek** [comment]
fixed in e12b176a2ec6bc02b7aac9e6f99e232c63793d0e
