### ISSUE TITLE
make peak text not selectable

### ISSUE THREAD

**Issue by stropitek** [cheminfo/nmr-displayer#109]
when zooming the peak values get selected

you can prevent it from being selected using css

**Comment by hamed-musallam** [comment]
the normal behaviour if you selected peak picking tool you can use brush tool to get the to pick the highest peak in the range,
The problem happend when you select zoom tool the first tool i mean from the top and zomm to specifc range and then select peak picking or integral tool it will add peak by default, this the problem what are facing.

**Comment by hamed-musallam** [comment]
it's done
