### ISSUE TITLE
Code auto formatting

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#11]
Please in VScode activate the options:

![image](https://user-images.githubusercontent.com/1484241/60296648-df8ede80-9926-11e9-9c2d-f64077ec039d.png)

and

![image](https://user-images.githubusercontent.com/1484241/60296766-149b3100-9927-11e9-80e8-84f63894251a.png)

**Comment by hamed-musallam** [comment]
I will enable it... thanks for advice.
