### ISSUE TITLE
design of icons for tool tips (peak picking, integral)

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#110]
Currently, they look quite the same and it is not intuitive to select the proper one

**Comment by lpatiny** [comment]
Please could you submit SVG proposal for the icons ? Or do you know somebody that could make all the icons related to NMR ?
We prefer to create them using InkScape and you could use the layout that is in the project http://github.com/cheminfo/font

**Comment by lpatiny** [comment]
Thanks !
