### ISSUE TITLE
peak picking take one point away from the true top

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#120]
Both on the 1H spectrum and FID, the peak picking takes not the local maximum point, but one point away fromt the true top.
![Screenshot 2019-10-29 09 50 23](https://user-images.githubusercontent.com/26463431/67751850-28b88180-fa32-11e9-9f64-605c12edd19a.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
We discuss about this point and it's related to way that the spectrum draw and the point position in pixels.

**Comment by lpatiny** [comment]
Need to find out how to fix this and also to be able to deal with the 'real top'.

**Comment by djeanner** [comment]
Beside the bug fix of the wrong point, I propose 3 solutions:
1) The "deluxe"  is to send the spectrum into a goog peak-picking (deconvolution?) which would give not only the true chemical shift (in the sense not the center of the top of the point, but the chemical shift corrected by the "pulling" effect of nearby peaks -if could resolve some coalesed peaks).
2) the "cheap" is to use spline (need only a few points near the top poin). It is better than the chemical shift from the point index. It is good to have in any case (I think).
3) "mid-level" is to use trigonometric interpolation but it is more demanding (even if shortcuts allows to avoid calculating the full spectrum - using a strip fft or something in this flavor I could look for if desired).

**Comment by djeanner** [comment]
![Screenshot 2019-11-08 17 42 25](https://user-images.githubusercontent.com/26463431/68497401-c000ae80-0254-11ea-9024-76d2d4971e1b.png)
It seems that the spectrum is plot shifted (possibly by one point).

**Comment by lpatiny** [comment]
I added a low-res simulated spectrum with known value. @hamed-musallam this is a bug in the scale / position of spectrum.
If you zoom in the spectrum you have
![image](https://user-images.githubusercontent.com/1484241/70691115-9a821d00-1cb8-11ea-9552-66761efc66d9.png)

While if you check at the data (after reduce) you see the 4th element that is the highest peak has the X value 0

![image](https://user-images.githubusercontent.com/1484241/70691231-dcab5e80-1cb8-11ea-9bf0-e7917f5fe3a3.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
first, we apply the auto peak picking into the original data, and reduce function actually i dont now alot about it, but what i get from the reduce function i display it correctly.

**Comment by lpatiny** [comment]
I'm not speaking about the auto peak picking. It is just that the data you receive are not correctly plot. There is a bug in the relative position between the spectrum and the axis
