### ISSUE TITLE
Zero filling / (trigonometric) interpolation

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#121]
Proposition to rename "zero filling" into "trigonometric interpolation". 

What the zero filling really does in this menu is a bit difficult to understand. If we look at a spectrum we are after processing so we do not expect to "zero fill". If we look at the FID, as a processing step, OK. If what the tool is doing is trigonometric interpolation (by zero filling) then I would call this interpolation. Also, we don't know how many points to ask for (not help - for 13C, larger window we may want more points than for 1H). Could the zero filling be chosen as zero-filling factor? (we would type "x4" instead of 131072 - in pt/Hz? or have any other guide for selecting the number of point)

**Comment by lpatiny** [comment]
Duplicate https://github.com/cheminfo/nmr-displayer/issues/122
