### ISSUE TITLE
zero-filling / trigonometric interpolation?

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#122]
What the zero filling really does in this menu is a bit difficult to understand. If we look at a spectrum we are after processing so we do not expect to "zero fill". If we look at the FID, as a processing step, OK. If what the tool is doing is trigonometric interpolation (by zero filling) then I would call this interpolation. Also, we don't know how many points to ask for (not help - for 13C, larger window we may want more points than for 1H). Could the zero filling be chosen as zero-filling factor? (we would type "x4" instead of 131072 - in pt/Hz? or have any other guide for selecting the number of point)

**Comment by djeanner** [comment]
PS: By the way, I wonder why interpolating (the full spectrum)!? In most cases, the interpolation could be done for a specific purpose (eg: measuring more precises coupling constants or get a better peak position), but this could be done **without interpolating the full spectrum** and have it interpolated in memory, but just interpolate the part that is on focus when the precision is needed). For 1D spectra, this may be ok, but for 2D, it will be aven more critical.

**Comment by lpatiny** [comment]
@djeanner as you see with the commit this is just the beginning of the developments of the filters in general and it is not expected to work correctly (active / inactive depending the kind of spectrum).
We prefer to develop directly on the main branch but you should not expect that everything works directly.
For general discussion you may join our monthly meeting is Friday 8 November at 5PM.

**Comment by djeanner** [comment]
Sure-I understand. I did not complain about anything not working. I will participate to the 8.11 meeting.
Damien
—————————————
e-Research/DLCM
University of Geneva
damien.jeannerat@unige.ch<mailto:damien.jeannerat@unige.ch>
—————————————
NMReDATA Initiative
nmredata.org
—————————————
NMRprocess.ch
damien.jeannerat@protonmail.com

On 29 Oct 2019, at 10:21, Luc Patiny <notifications@github.com<mailto:notifications@github.com>> wrote:


@djeanner<https://github.com/djeanner> as you see with the commit this is just the beginning of the developments of the filters in general and it is not expected to work correctly (active / inactive depending the kind of spectrum).
We prefer to develop directly on the main branch but you should not expect that everything works directly.
For general discussion you may join our monthly meeting is Friday 8 November at 5PM.

**Comment by lpatiny** [comment]
Zero filling was implemented
