### ISSUE TITLE
Manual phase correction - how to ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#124]
While the algorithm to correct the phase has been implemented:

https://github.com/mljs/spectra-processing/blob/master/src/reim/phaseCorrection.js

this algorithm requires ph0 and ph1.

However when we manually phase a spectrum we can directly act on ph0 but we don't change directly ph1 as it depends of a pivot.

How we convert the change on 'ph1' to real ph0, ph1 based on the pivot point ?

There could be some code in this: https://github.com/cheminfo/hook4/tree/master/src/org/cheminfo/hook/nemo

**Comment by jobo322** [comment]
@lpatiny about manual phase correction, I think it's difficult to condense all changes from manual phase correction tool into a single filter. Imagine that during phase correction procedure, the user changes two times the vertical indicator position (pivot index for PC algorithm) with changes ph1 value in each position, to reapply filters and get the same state of data, we should save two phase correction filters each with a pivotIndex and overall changes of ph1.

**Comment by djeanner** [comment]
I hope I got this right... I have to say that I decude the method you used from what you write, not by looking at the code... If I'm wrong, please point to the code so that I can be more relevant.
![Screenshot 2019-11-25 08 06 31](https://user-images.githubusercontent.com/26463431/69519599-b6688d80-0f5a-11ea-8981-d24696f51ded.png)

**Comment by djeanner** [comment]
I forgot to say... that doing it as mentionned here should solve the problem of multiple change in pivot position or multiplet phase step, but they would simply update pivot-independant corrections.

> I hope I got this right... I have to say that I decude the method you used from what you write, not by looking at the code... If I'm wrong, please point to the code so that I can be more relevant.
> ![Screenshot 2019-11-25 08 06 31](https://user-images.githubusercontent.com/26463431/69519599-b6688d80-0f5a-11ea-8981-d24696f51ded.png)

I forgot to say... that doing it as mentionned in

**Comment by jobo322** [comment]
Thanks for your help @djeanner, it was useful to reduce manual phase correction filter.

**Comment by lpatiny** [comment]
Implemented
