### ISSUE TITLE
Create React components for annotations

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#13]
First annotations could be a peak label

One way is to draw a vertical line that is just on top of the peak with the value next to it like:

![image](https://user-images.githubusercontent.com/1484241/60538839-a8944080-9d0b-11e9-8a76-0e3faa427443.png)

Would be nice that this value can optionaly be edited

**Comment by hamed-musallam** [comment]
i implemented the this feature, you check it at the current version at githup
