### ISSUE TITLE
How do we call the linebroadening function?

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#130]
How do we call the line broadening function (see my pull request for initial implementation)? I mean: where to click?

**Comment by hamed-musallam** [comment]
@djeanner 
you can apply the zero filling filter only when the spectrum is FID spectrum, you can examin this t in 13C FID example, you will find button called Zero, select it and then it will display list of filter sizes to apply it into the spectrum.

**Comment by djeanner** [comment]
... yes, but now, after clicking "zero" I have only the zero filling that I can select (pull down). I cannot apply the others... (I'm on the master branch... is it the correct one ?)

**Comment by hamed-musallam** [comment]
@djeanner 
you need first to add peak and after that, you can shift the spectrum over the x-axis by changing the value in the peak by click on the text and change the value and press enter to apply changes.

**Comment by djeanner** [comment]
For the lineBroadening, I see that it is not in the FiltersToolBar - this is why I cannot use it yet.
