### ISSUE TITLE
maintaining the dependencies up-to-date

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#140]
Please maintain the project at least once a week

```
ncu -u
rm -rf package-lock.json node-modules
npm i
```

To install ncu you should install globaly: https://www.npmjs.com/package/npm-check-updates

**Comment by hamed-musallam** [comment]
@lpatiny 
the commands you provide it at the top it's specific for MacOS

**Comment by lpatiny** [comment]
It is not specific to OsX. We are working on mac. linux and windows. Did you install `ncu` globally as pointed by the link in the ticket ?

**Comment by hamed-musallam** [comment]
> It is not specific to OsX. We are working on mac. linux and windows. Did you install `ncu` globally as pointed by the link in the ticket ?

I install ucu globally using command npm i -g ucu and when run your command give me 
NCU Real Time Weather is Running......!!!!!!

**Comment by lpatiny** [comment]
You didn't check the URL. The command is ncu but the package npm-check-updates as explained here:  https://www.npmjs.com/package/npm-check-updates
