### ISSUE TITLE
source code contains CSS=[Object Object]

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#141]
![image](https://user-images.githubusercontent.com/1484241/68402969-7cd30c80-017c-11ea-9946-0790dab92f2f.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
because we use emotion js library [https://emotion.sh/docs/introduction](url) for styling things in our project.

**Comment by lpatiny** [comment]
You need there is a bug in emotion ? You can fill a ticket ?

Because in other projects using this library this does not happen.

**Comment by lpatiny** [comment]
By the way did you import emotion in that file ? Because CSS property should have been replaced.

**Comment by hamed-musallam** [comment]
I fix this problem.
