### ISSUE TITLE
Refactor filters

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#144]
Datum1D should not directly call the filters but have a method of the kind

`applyFilter(filterName, options)`

This method with deal with previously existing filters, check if it have to be applied only once, etc.

This method will execute `Filters[filterName](datum1d, options)`

https://github.com/cheminfo/nmr-displayer/blob/91fa8e48549d5c5691ea7a75d6101c6ac898876a/src/data/data1d/Datum1D.js#L125-L126

We should never change datum1D anymore to create new filters.

**Comment by lpatiny** [comment]
@hamed-musallam I would like that you create a FilterManager that will deal with applying filters, check if was was already applied and decide how to update (if possible) based on the filter reduce preferences, etc.

https://github.com/cheminfo/nmr-displayer/blob/86b932878f9b69c52d9f143a12497a0eb3f47d45/src/component/reducer/Reducer.js#L427-L428

Should become something like:
```
activeObject.applyFilter([
{name: 'zeroFilling', options: {}},
{name: 'lineBroadening', options: {}},
]);
```

**Comment by hamed-musallam** [comment]
@lpatiny 
Done, can you check what i did in the last commit.

**Comment by lpatiny** [comment]
LGTM
