### ISSUE TITLE
Please don't copy paste code !!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#146]
Please create a function instead of copying twice the code

https://github.com/cheminfo/nmr-displayer/blob/91fa8e48549d5c5691ea7a75d6101c6ac898876a/src/component/reducer/Reducer.js#L437-L449

https://github.com/cheminfo/nmr-displayer/blob/91fa8e48549d5c5691ea7a75d6101c6ac898876a/src/component/reducer/Reducer.js#L528-L541

**Comment by hamed-musallam** [comment]
done
