### ISSUE TITLE
Clicking on phase correction does not desactivate the other tool

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#147]

**Comment by hamed-musallam** [comment]
so you need to deactivate the other tool when phase correction filter is selected, but this is what happen if not can you clarify what you need because i have some misunderstanding.

**Comment by lpatiny** [comment]
I think the easiest is that all those icons

![image](https://user-images.githubusercontent.com/1484241/68776479-6de2d300-0630-11ea-9441-59c282c8c86a.png)

Are part of the same group and only one of them can be selected at the same time. If you are in the phasecorrection and click on the zoom the phasecorrection should be desactivated and the inputbar on the top should be removed.

**Comment by hamed-musallam** [comment]
but for now i have tow different group, group for Filters and the other one for tools

**Comment by lpatiny** [comment]
Yes I think this should be changed to have only one group
