### ISSUE TITLE
Scale is strange when zooming too much

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#15]
We have overlap of the numbers

![image](https://user-images.githubusercontent.com/1484241/60538540-1c821900-9d0b-11e9-9f66-734f0d7aa3b4.png)

**Comment by hamed-musallam** [comment]
because it have alot of tickets so if we reduce the number of tickets along x axis i'm sure it will solve he problem or my be  we can format the number.

**Comment by hamed-musallam** [comment]
i choose to go with the first  solution that mean i reduced the number of tickts along x axis.
Close #15
