### ISSUE TITLE
Auto peak picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#152]
@hamed-musallam Please prepare an action button 'Auto peak picking'

@djeanner Could you prepare icons for auto peak picking and range peak picking. The range peak picking allows to create not just a single pick but also find the multiplicity (which is quite different from the icon we have currently)

@jobo322 Could you check how we can execute the smart peak picking we have now on a simple XY data. You can link us the existing code ?

**Comment by djeanner** [comment]
I made the new icons.

**Comment by lpatiny** [comment]
@hamed-musallam After validation (or cancelation) of the auto peak picking please select the 'zoom' button in the toolbar.

**Comment by hamed-musallam** [comment]
it's implemented
