### ISSUE TITLE
Manual range analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#153]
While currently we have a peak picking and an integral this was mainly for experimenting.

@michaelwenk could you start the range selection. A range corresponds to an integrated part that may contain one or more signals
- [ ] create a new panel 'ranges'
- [ ] create a new button 'Create range' (similar to integral)
- [ ] create the logic that when you create a range (like in the integral) adds the corresponding from / to and integral
- [ ] draw the range under the spectrum with the value of the integral

Please ask @hamed-musallam if you need help

Here you find the current description of ranges (that contains signals that contain couplings):
![image](https://user-images.githubusercontent.com/1484241/68526498-db170100-02dc-11ea-96ac-1d1a980a0364.png)

**Comment by michaelwenk** [comment]
@lpatiny I can try this. Why are some of them yellow marked?

**Comment by lpatiny** [comment]
Because it was either new or in discussion.
@jobo322 will add the auto peak picking that we have and that will generate the ranges object. You may therefore create a dummy one so that you can create the react component to display it and the panel to display and maybe edit them.
