### ISSUE TITLE
Create a new component to draw multiplicity

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#154]
From the ranges / signals / multiplicity object structure we should be able to annotate the spectrum with the multiplicity.

Something like:

![image](https://user-images.githubusercontent.com/1484241/68526588-0bab6a80-02de-11ea-8509-4db374609249.png)

You can get inspired by the following code https://gist.github.com/lpatiny/5956d1866998fc565d4c676cf4a2be3b

This could be a toggle option at the level of the spectrum to show / hide this kind of annotation

**Comment by djeanner** [comment]
The green is a split due to coupling to a spin 1/2, 
 - blue with spin 1 and 
 - purple with spin 3/2, 

or you mean 
 - triplet and 
 - quartet?
I you mean the second, I propose that when writing this code you have in mind spin>1/2 otherwise it will require useless rewriting.

**Comment by lpatiny** [comment]
Only for spin 1/2 as you can see in the source code (using pascal triangle): https://gist.github.com/lpatiny/5956d1866998fc565d4c676cf4a2be3b#file-example-of-code-to-draw-multiplicity-L91-L97

@djeanner If you now how to generalise this formula for any spin please change this part of the code.

**Comment by djeanner** [comment]
I did it [here](https://github.com/cheminfo/nmredata/blob/dj_test_function/src/getPascal.js)
here is a copy because I'm not sure you have access.
----------------------------
```javascript
export default function getPascal(n, spin) {
  line = [1];
  if (n === 0) return (line);
  var mult = 2 * spin + 1;
  for (var j = 0; j < mult - 1; j++) line.push(1);
  // complete with "1 1" or "1 1 1" for spin 1/2 and 1 respectively
  var previousLine = line;
  for (var i = 0; i < (n - 1); i++) {
    var line = [];
    for (j = 0; j < mult; j++) {
      if (j === 0) {
        for (var k = 0; k < previousLine.length; k++) line.push(previousLine[k]);// copy the line
      } else {
        for (k = 0; k < previousLine.length - 1; k++) line[k + j] += previousLine[k]; // add the previous line
        line.push(1); // complete the line
      }
    }
    previousLine = line;
  }
  return line;
}
```
