### ISSUE TITLE
problem in phase correction filter

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#157]
@lpatiny 

https://github.com/cheminfo/nmr-displayer/blob/efaa12b570dda1f73c2a32fba70ad346eca4e59f/src/data/data1d/filter1d/phaseCorrection.js#L19-L22

**Comment by lpatiny** [comment]
What is the problem ?

**Comment by hamed-musallam** [comment]
> What is the problem ?

It indeed not have any effect on datum1D.data, and also why he return to original data and not the last state of the data.

**Comment by lpatiny** [comment]
@jobo322 Please have a look at this.
Please take care that the way I see it is that we interactively phase the spectrum and once we click 'done' there is the actual filter that is added to the list of filters.
