### ISSUE TITLE
add digital filter

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmr-displayer#160]
There is missing a important filter to get a good NMR spectrum from Bruker data, some information about it [digital filter from nmrglue](https://nmrglue.readthedocs.io/en/latest/reference/generated/nmrglue.fileio.bruker.remove_digital_filter.html) package

**Comment by lpatiny** [comment]
@djeanner @nes-cgn How this filter is applied in other software ? Transparently ?

**Comment by jwist** [comment]
yes, it is done along with the FT, the user is not aware of it

Julien

Director de la Oficina de Transferencia
de Resultados de Investigación -OTRI
Dr.Sc. Assistant Professor (Chemistry Department)
Universidad del Valle, Cali, Colombia
website: http://www.cheminfo.org


*AVISO LEGAL:* Este mensaje y/o sus anexos son confidenciales y para uso
exclusivo de su destinatario intencional. Si usted no es el destinatario,
le informamos que no podrá usar, retener, imprimir, copiar, distribuir o
hacer público su contenido. Cualquier retención, revisión no autorizada,
distribución, divulgación, reenvío, copia, impresión, reproducción o uso
indebido de este mensaje y/o anexos, está estrictamente prohibida y
sancionada de acuerdo con la Ley 1273 de enero del 2009. Si ha recibido
este correo por error, por favor elimínelo e infórmenos al correo
xxxxxx@correounivalle.edu.co Si usted es el destinatario, le solicitamos
mantener reserva sobre el contenido, los datos o información de contacto
del remitente y en general sobre la información de este documento y/o
archivos adjuntos, a no ser que exista una autorización explícita.

**Comment by djeanner** [comment]
> @djeanner @nes-cgn How this filter is applied in other software ? Transparently ?

I don't understand the question.

**Comment by djeanner** [comment]
The digital filtering itself is done in the firmware of the NMR spectrometer. But the data need to be rotated by a certain number of points (_n_ first points have to be moved to the end - _n_ probably depends on the digital filter parameters).I guess that this operation is done by the above-mentionned **digital filter from nmrglue** package

**Comment by lpatiny** [comment]
@jobo322 Please could you add the code in: https://github.com/cheminfo/nmr-displayer/blob/935dcd086b368a7ec62fa3782fbe02b35b2753ca/src/data/data1d/Datum1D.js#L86

**Comment by jobo322** [comment]
I put the code in filter1d folder, did I do well?

**Comment by nes-cgn** [comment]
Yes!
