### ISSUE TITLE
manual phase correction is wrong

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmr-displayer#161]
The manual phase correction updates datum1D.data. It means that if you want to reapply the filter (it's normal) you need to apply it with the difference between current value and previous one to get the correct behavior. the new inputRange to update ph0 and ph1 values is nicer but the filter is applying with the current value

example 
first, update ph0 to
ph0=90 , ph1=0  // the data rotate 90 degrees
second update ph0
ph0=91 , ph1=0 // the result is data rotated 181 degrees, we need to apply a rotation of 1 degree (the difference) to get data rotated 91 degrees

**Comment by lpatiny** [comment]
And what about ph1 ?

**Comment by jobo322** [comment]
The same, I'm working to have a prototype working that i can show you
