### ISSUE TITLE
user-select: none

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#163]
When double click the text of the cursor is selected and the label of the scale as well. A lot of elements should have the CSS property user-select: none

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by hamed-musallam** [comment]
i did it from yesterday, but i'm working on changing peak notation to be lighter.

**Comment by lpatiny** [comment]
Ok cool. You may add at the top level a rule to prevent selection on any content of <svg>

Don't know if it was done like that.

![image](https://user-images.githubusercontent.com/1484241/68758257-bf2d9b00-060d-11ea-85a1-918a1476b1f9.png)

**Comment by lpatiny** [comment]
Still the case with peak labels

![image](https://user-images.githubusercontent.com/1484241/70270918-a2682b80-17a5-11ea-9c65-668ca636569d.png)
