### ISSUE TITLE
copy and concat array

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#166]
To copy an array please use 'slice' and not [...

(you can find all the occurence in your code by searching for '[...'

let arrayCopy = array.slice(0);

To join 2 arrays dont use `this.peaks = [...peaks, ...this.peaks];` but use `concat`

**Comment by hamed-musallam** [comment]
@lpatiny 
Can i now why array.slice(0) bettter than [...]?

**Comment by lpatiny** [comment]
It is 40 times slower

![image](https://user-images.githubusercontent.com/1484241/68768110-2ce3c200-0622-11ea-9479-7a0748d64e81.png)

You may always test using https://jsbench.me/

**Comment by hamed-musallam** [comment]
@lpatiny  
what about using Object.assign([], array)

**Comment by lpatiny** [comment]
I expect the same speed as [...a] so 40x slower but feel free to try it on jsbench.
