### ISSUE TITLE
spectrum-chart.css should be removed and replaced by emotion

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#167]
spectrum-chart.css also applies CSS rules on body preventing to include this component in another project.

**Comment by hamed-musallam** [comment]
i try to use global components from emotion js library and put it in nmrDisplay but i did not get any affect, many of the css selectors  it's for global selectors ,like shape of the scrollbar  and splitpanel and soo on,

**Comment by lpatiny** [comment]
No CSS should be global. You need to add the CSS to the React components and for example for the font-family in the NMRDisplayer component.

**Comment by hamed-musallam** [comment]
No some css must be global like the shap of scroll bar, the other things i try to override the inline css use by split panel and i use emotion js for it and it's not work .
i tryied this before you open this ticket, and as you can see this only css file

**Comment by lpatiny** [comment]
You may get rid of scroll bar CSS and the overflow:hidden should be in the dashboard css. Because it is a component that will be reused in other webpage really nothing may be global. All that is related to split and resize should go in the corresponding component.

**Comment by hamed-musallam** [comment]
done
