### ISSUE TITLE
phase correction: improve user interaction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#176]
The following could be changed (same fonctionality as the zoom button):
* vertical mouse wheel scroll should scale the spectrum
* double click should zoom out the spectrum (X axis)
* click + drag + release to zoom in

More over during phase correction (changing PH0 and PH1) we should keep the Y axis fixed so that the spectrum does not move vertically.

**Comment by hamed-musallam** [comment]
this the point that i spoke about it before that we have tool and filter at the same time. so the best result is to have the zoom tool selected and the phase correct is selected at the same time

**Comment by lpatiny** [comment]
I don't agree. For all this group of button only one should be selected at a time
![image](https://user-images.githubusercontent.com/1484241/68872552-815c6f80-06fe-11ea-97d9-ed175f1d0cab.png)
And the top bar to enter custom values for the filter should be only present if the corresponding button is selected.

All the buttons should have as default behaviour:
* vertical mouse wheel scroll should scale the spectrum
* double click should zoom out the spectrum (X axis)
* click + drag + release to zoom in

And each button mais overwrite those default behaviour (Object.assign).
* Peak picking change the behaviour of  click + drag + release to make peak picking in a range
* Integration change  click + drag + release to add integral and vertical wheel to scale integral
* etc.

We should also be able to deal with modifier keys (ALT and SHIFT) and probably we will add a combination that allows to pan the spectrum.
