### ISSUE TITLE
Scroll and vertical scale

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#18]
Currently the vertical scroll seems limited and it looks like you continue to scroll but the spectrum does not scale.  And after scrolling down look like you first need to reduce to a limit before the spectrum is scaled down.

Please remove the limitation. You may scroll up / down as much as you want.

**Comment by hamed-musallam** [comment]
I think the limitation is related to the y-axis domain because it starts from 0, so the domain I think can't be lower than 0.

**Comment by hamed-musallam** [comment]
i solved this issue, by modify the code to allow the user to scale up and dow as much as he need with out any constantins.

Close #18

**Comment by lpatiny** [comment]
In the last build I still have strange behaviour.

**Comment by hamed-musallam** [comment]
can you explain what happen with you,what do you mean in strange behavior because i tested it many times during the development  and it's seems to me everything works good.

**Comment by lpatiny** [comment]
For me it still does not work. On my mac if I make with a macbook a very fast vertical scale suddenly it stops scaling.
I tried to check the wheel events using https://github.com/d3/d3-zoom/blob/master/README.md#zoom_wheelDelta and it is correct
