### ISSUE TITLE
default mouse events

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#180]
There should be a system that allows whichever button is selected to have some default mouse behaviour.

The default corresponds to the current 'select' button.

The following mouse events should be considered:
- click
- double click
- click drag release
- mouse wheel

Moreover all those events are associated with modifiers (shift or alt)

The default behaviour is:
- no shift, no alt, double click :> full zoom out
- no shift, no alt, click drag release -> zoom
- no shift, no alt, mouse wheel -> vertical scale

**Comment by lpatiny** [comment]
There should also be the 'zoom' effect (zone of the zoom is displayed) when you zoom horizontally with another tool.

**Comment by hamed-musallam** [comment]
@lpatiny 
did you auto peak picking and auto ranges picking, why it's need it and you can apply the filter and then you can zoom.

**Comment by lpatiny** [comment]
For phase correction for example you will need to zoom to adjust the phase.

**Comment by hamed-musallam** [comment]
@lpatiny 
for phase correct you can zoom, i tested it on the last version of the project.

**Comment by lpatiny** [comment]
In the auto peaks mode you can also zoom but you are not visual feedback. Same with true when you do a zoom in the zeroFilling mode. Can you do something general ? All those action should have the same behaviour.

**Comment by hamed-musallam** [comment]
@lpatiny 
its need more thinking to have general solution, we will do it in our way during development.
