### ISSUE TITLE
Improve code in getDomain

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#19]
https://github.com/cheminfo/nmr-displayer/blob/1d1a5ebf0c0ba034f92aa6a22989f1a8106e1c8d/src/component/spectrum-chart.jsx#L72-L81

If you want to extract a property from an array of object please replace
```
let xArray = [];
let yArray = [];
for (let d of data) {
      xArray = xArray.concat(d['x']);
      yArray = yArray.concat(d['y']);
    }
```
by
```
let xArray = data.map( d => d.x);
let yArray = data.map( d => d.y);
```
It will be at least data.length faster

I guess also for 'x' the min / max will be data[0].x and data[data.length-1].x

**Comment by hamed-musallam** [comment]
but you suppose here that there will be one path per chart. if that what you want to be implemented that actually what I attending to do from the first time.. but suppose you have multi-paths at the same chart how you will find the domain for the whole chart?

**Comment by targos** [comment]
I think the best would be to compute the domain for each series separately and then combine them. Copying big arrays is very costly for memory and cpu

**Comment by lpatiny** [comment]
For X we know:
min: d.x[0]
max: d.x[d.x.length-1]

**Comment by hamed-musallam** [comment]
Close #19

**Comment by hamed-musallam** [comment]
close #19

**Comment by targos** [comment]
@hamed-musallam The `Close #issue` line should be in the commit message of the corresponding commit. Then GitHub closes the issue automatically and links to the commit.
