### ISSUE TITLE
Display spectrum with zoom

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#2]
Use D3 library to create SVG for axis and spectrum

Many components:
- Axis
- Spectrum1D

Zoom
- vertical zoom with scroll wheel or 2 fingers vertically
- horizontal zoom click + drag (should show a rectangle + release)

Get inspired:
https://www.c6h6.org/
Click once on ethylbenzen and then on `1D NMR peak picking`

-

**Comment by hamed-musallam** [comment]
i implemented it and ready for test, @lpatiny Did i build what you need or not ..
