### ISSUE TITLE
'Zero' should be aligned

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#202]
For all the spectra (when superimposed and not stacked) the zero position should be at the same position. This means that in the DEPT example all the noises should be superimpose and not like now. This is also true when spectra are scaled.

![image](https://user-images.githubusercontent.com/1484241/70266999-d3446280-179d-11ea-8aea-ff5dbd9fc42b.png)

**Comment by lpatiny** [comment]
The dept are not exactly on the same line and they should be.

In the case of DEPT the spectra have to be center on the screen. Meaning that the zero should not be in the bottom of the displayer but in the middle.

It could be an option (toggle button) to be centered or in the bottom.

**Comment by lpatiny** [comment]
Still missing an option that allows to toggle between setting the 0 in the bottom or in the middle (like in a FID btw).

**Comment by hamed-musallam** [comment]
it's done.

**Comment by lpatiny** [comment]
Full out ('F') does not remember this option.

Is this option saved in the json ? It should be there by default for this set of data (DEPT)

**Comment by lpatiny** [comment]
Preferences should be saved maybe in preferences.1d.display.XXX
