### ISSUE TITLE
Improve integrals to assign a kind to the signal

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#206]
In the integral panel add a column to specify the signal kind among the following list, the default being 'signal'

![image](https://user-images.githubusercontent.com/1484241/70268675-3be10e80-17a1-11ea-84a6-766c646333f6.png)

In the header of the integral if nucleus is 1H display a small input text box 'nbH' that by default contains `molecule.atoms.H || 0`

We will have to rescale the column Integral so that the sum corresponds to this total value.

**Comment by lpatiny** [comment]
@michaelwenk The same principle will be applied on ranges.

**Comment by hamed-musallam** [comment]
@lpatiny 
from where i can get molecule.atoms.H?
