### ISSUE TITLE
Highlight between table and annotations

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#212]
Create a way to have highlight between table and annotations. Because there is already highlight on mouse over for ranges we could start with this one.

The goal is that a mouse over the table show the line in yellow and highlight the corresponding annotation in the spectrum

@michaelwenk Do you think you could help on this ?

**Comment by michaelwenk** [comment]
@lpatiny I now implemented a way to highlight a row in the ranges table (same color as a range rectangle, orange) when the mouse is over a range in the spectrum. Therefore I'm using a new property in ranges which is stored as "_highlight" which also could be stored for each object we want and give that object to a ReactTable component which then will highlight that range (or object) with "_highlight === true". I think I saw that same or similar way in the Visualizer project on GitHub some months ago.

The other way around is the next step.

**Comment by lpatiny** [comment]
Please make a pull request. It is an important functionality and it would be nice if @targos review this pull request.
