### ISSUE TITLE
Panel preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#215]
Each panel (integral, peak, range) could have preferences in the little menu bar that should be added.

The preferences will be a gear icon.

It will let appears panel preferences that will be stored in the analysis in:
```
    this.preferences = {
      panels: {
        '1H': {
          integrals:{},
          peaks:{},
          ranges:{},
        },
        '13C': {
          integrals:{},
          peaks:{},
          ranges:{},
        }
      },
      display: {},
    };
```
that exists for this purpose

The preferences of the panels will be nucleus related in order to plan the future in which we have in the same display different spectra and we need to specify a different number of decimals depending if it is a proton or a carbon for example.

As an exercise we can add for the peaksPanel the following options
* δ (ppm) : show / hide, number decimals: 2
* 𝜈 (Hz) : show / hide, number decimals: 4
* peak width : show / hide; number decimals: 3

This principle will be expanded to the other tools as well

I like the idea that preferences are 'behind' the card and I wonder if the form could be flipped using https://www.npmjs.com/package/react-card-flip (Demo: https://aaronccwong.github.io/react-card-flip/). So when you click on the small gear the table flips and you see the preferences.

**Comment by lpatiny** [comment]
this will be important to debug peak picking results. I added some simulated spectra and the peak picking is not aligned. Would like to know the value that is found with all the decimals.

![image](https://user-images.githubusercontent.com/1484241/70567552-6f9fa800-1b96-11ea-8642-4345a074070d.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
do you mean the auto peak picking, i will check it and inform you what is the result, but the manual peak picking is working fine and it's depend on the index of the x so all what i did i took the array of index that generated from auto peak picking fnction and display it, how i can know if the index is correct?

**Comment by hamed-musallam** [comment]
@lpatiny  
Panel preferences, i can't imagine what you need exactly from me to implement.

**Comment by lpatiny** [comment]
Each panel (peaks, integrals, etc) may have some options like the number of digits. So next to the delete icon there could be a little gear to display preferences of this pannel as described above.

Those preferences should be saved in the json.

**Comment by hamed-musallam** [comment]
@lpatiny     
this.preferences = {
      panels: {
        'spectrum id': {
          integrals:{},
          peaks:{},
          ranges:{},
        },
      display: {},
    };

i think it's better if we use spectrum id and according to the selected spectrum it has different options

**Comment by lpatiny** [comment]
I don't expect to have specific preferences per spectrum and would like to be able to reuse the preferences for another set of spectra so it is better that it is based by nucleus and not spectrum id.

**Comment by lpatiny** [comment]
I don't expect to have specific preferences per spectrum and would like to be able to reuse the preferences for another set of spectra so it is better that it is based by nucleus and not spectrum id.

**Comment by hamed-musallam** [comment]
it's done;
