### ISSUE TITLE
Website for exercises

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#216]
The goal is to use the current stage of the application to create exercises.

A 'end-user' should be able to drag and drop 1D experiments as well as a molfile to discover.

There should be some general preferences for the react component allowing to define which tools and panels are available.

There will be a new project that will depend on nmr-displayer. It will also include react-ocl and openchemlib.

It will generate a website that contains various exercises in a hierarchical menu. While all the exercises are 'just' a JSON created with the current tools the component being presented to the user will depend from one exercise to another.

One of the exercises will be the structure elucidation. This exercise will include `nmr-displayer` and `react-ocl` in the editor mode. The student will be able to zoom, integrate, etc and to draw the molecule. This page will also check if the answer is correct or not.

**Comment by hamed-musallam** [comment]
done
