### ISSUE TITLE
Demo website seems too complex to maintain

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#217]
The demo website requires too much code add seems much to complex.  Adding a new example requires the creation of a . new component.

This should be redone from scratch with only basic libraries.
There should be only one configuration file in which we describe an array of objects. The object should contain the URL to the json and a description (the name that will appear in the menu).
There should be the possibility to have a well a submenu (or subsubmenu) (children). By default submenu are closed and you may click to open them.

Once this is done we need to to have the new 'predicted' spectra that are now available and that should be part of a submenu.

This same basic website will be used for the first series of exercises.

For the menu on the left this component could be used: https://www.npmjs.com/package/rc-menu and in particular the example in the bottom of the following page:
https://menu.react-component.now.sh/?selectedKind=rc-menu&selectedStory=antd&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by hamed-musallam** [comment]
it's done, all what you need is generate the the samples and insert the path of the generated json file inside samples.json under demo folder
