### ISSUE TITLE
Foreseen different layouts in samples.json

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#221]
We should plan that in the demo we have different layout that are nicely organised.

One of the layout is the current one, called "Default". We will have another one called 'StructureElucidation".

To do:
- in samples.json allow a new property called `layout`, by default: `Default`
- create a new layout called `StructureElucidation` that is similar to the current one but also contains a react-ocl component in edition mode.

**Comment by hamed-musallam** [comment]
@lpatiny
can we discuss about this, because i really need to understand what exactly the shape of the page well be according to specified layout in sample json file.
