### ISSUE TITLE
Prepare files for exercises

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#225]
Please prepare as much as possible files for exercises and use the following structure to send them to me (zipped by telegram):
- folder name = cas number + space + description (optional)
  - structure.mol
  - 1h.jdx
  - 1h.fid.jdx
  - dept.jdx
  - dept.fid.jdx
  - cosy.jdx
  - cosy.fid.jdx
  - ... (apt, tocsy, roesy, noesy, hsqc, hmbc, jresolv, ...)

Each folder will containg a molfile called 'structure.mol' and all the 1D and 2D with always (if possible) the jcamp before FT and after FT.

Depending the exercises the student will have to make the FT or not.

I will combine all the spectra and we will create a webpage that allows to create easily new exercises based on them.

**Comment by nes-cgn** [comment]
Dear Luc, I will start working on that this weekend. I got usually APT or DEPTQ spectra for C-13.

**Comment by lpatiny** [comment]
@nes-cgn thanks for the file. I uploaded them in a new project: https://github.com/cheminfo/nmr-dataset1

We only need .mol (and no .sdf) and the file could be name structure.mol
