### ISSUE TITLE
Possibility to change the sum of integral

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#234]
In the integral menu add an icon '∑' that allows to set (and therefore force) the integral. Default value should come from the chemical structure (as it is now). If the value is not forced we will always take the value from the first molecule. If it is forced we will not change it.

**Comment by hamed-musallam** [comment]
@lpatiny 
did you mean the menu on the top of the internal table in the integral panel? or you mean in the table row and what happen if we dont have any molecule?

**Comment by lpatiny** [comment]
In the top on the internal panel. We may always set a total value even if we don't have a molecule. The default value without molecule could be 100.

**Comment by hamed-musallam** [comment]
@lpatiny 
can you explain step by step what do you need me to do, because i'm confused, why we need to have the total of integrals in the top panel.

**Comment by hamed-musallam** [comment]
@lpatiny 
What we have to do in this point, i made the changes that you requested in the integrals,ranges and peaks to have {options:{},values:{}},but what is the next?

**Comment by lpatiny** [comment]
@hamed-musallam I prepared the code but you need to finish it because I'm currently changing a readonly property and it crash. Should be easy for you.
