### ISSUE TITLE
Add new export: Copy formatted string

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#235]
This should call

spectra-data-ranges

`getACS(ranges)`

It returns an HTML formatted string that could be displayed in a dialog box with a copy to clipboard icon

It is important to be able to preview this string and give the possibility to select it

**Comment by hamed-musallam** [comment]
@lpatiny 
you mean we have library call spectra-data-ranges and it's contain function call getACS(ranges), it take ranges as parameter and the output from it will be html string and then we need to export the result as HTML, is that right?

**Comment by lpatiny** [comment]
Yes I added this dependency this morning

**Comment by hamed-musallam** [comment]
@lpatiny 
But what do you mean in ranges because when we apply auto ranges is for specific spectrum.

**Comment by lpatiny** [comment]
You may put the export button in the ranges panel menu

![image](https://user-images.githubusercontent.com/1484241/71176298-d5acbf00-2269-11ea-9942-0efa2270a4d0.png)

You need to send the function the array that is displayed in this panel

**Comment by lpatiny** [comment]
The content is HTML and should be displayed as HTML (currently the HTML is escaped, something like innerHTML should be used). The `1` should be in upperscript.

<sup>1</sup>H NMR: δ 7.29-7.32 (7H, m), 6.33-6.35 (7H, m), 6.00-6.02 (7H, m), 4.02-4.06 (8H, m), 3.81-3.86 (8H, m), 2.97-3.11 (32H, m), 2.90-2.92 (8H, m), 2.31-2.34 (1H, m), 2.31-2.34 (6H, m), 2.14-2.15 (1H, m), 1.94-1.96 (13H, m), 1.94-1.95 (2H, m), 1.94-1.94 (0H, m).
