### ISSUE TITLE
Disable filter may yield to errors

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#236]
You can from a FID make all the treatment and then you have the possibility to switch off some filters.

Problem raises if you apply FT and then filters that require FT spectra (like phase correction). If you desactivate FT it will crash

```
Uncaught Error: phaseCorrection not isApplicable on this data
    at Module.apply (:3000/static/js/main.chunk.js:12050)
    at Function.enableFilter (:3000/static/js/main.chunk.js:11445)
    at Datum1D.enableFilter (:3000/static/js/main.chunk.js:11230)
```

I think when applying filters we could just ignore them if they are not applicable and not throw erros.

We can also think about a new panel with logging information. This will soon or later be useful.

**Comment by hamed-musallam** [comment]
@lpatiny 
we have two cases:
1. enable and disable filter.
2. delete filter.
What the normal behaviour for both cases if the filter not applicable.

**Comment by lpatiny** [comment]
What would be nice is that in all the cases there is no error but also that in all the cases there is a visual feedback in 'filters'

![image](https://user-images.githubusercontent.com/1484241/71159205-82287a00-2245-11ea-9dd6-e85f51f2a527.png)

Instead of the value you could but in red the message to show that it is not executed.

**Comment by hamed-musallam** [comment]
@lpatiny 
visual feedback in 'filters', do you mean small spectrum visualizer, if that true, we have to save the spectrum data at least the x and y for when apply each filter.

**Comment by lpatiny** [comment]
I mean just replace the Properties of the filter with the error in red
