### ISSUE TITLE
Simplify peak picking and range picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#237]
We should combine manual and automatic peak and range picking.

The idea is that is you press 'p' for peak picking you are in the manual peak picking mode and you can start to manually select peaks but at the same time the top bar change to the automatic peak picking

![image](https://user-images.githubusercontent.com/1484241/71152904-01af4c80-2238-11ea-9fd8-55d7110c8a51.png)

Same if true for range peak picking when you press 'r'

This will reduce the number of buttons while keeping all the functionalities.

**Comment by hamed-musallam** [comment]
@lpatiny 
Only when press p or do you mean we have only one button in the toolbar for peak picking and you can perform both manual and auto.

**Comment by lpatiny** [comment]
Not only when you press p. Only one button in the toolbar for peak picking.
