### ISSUE TITLE
Group spectra by kind

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#243]
When we drag and drop spectra we should group them by kind. Kind being defined in fact by the same nucleus.
So we have many spectra there will be a category for
- 1H (1D spectrum)
- 13C (1D spectrum)
- 1H / 1H (2D spectrum)
- 1H / 13C (2D spectrum)
- ...

A 1D component may only display one category of spectra, same is true for 2D component. Should not forget however that in the future for 2D spectra we will have one 2D component and 2 1D component.

I propose that just under the Spectra header of the panel we display tabs with the name of the tab being the nuclus ('1H', '13C', '19F', '1H/1H', ... if any of those spectra are available.

![image](https://user-images.githubusercontent.com/1484241/71188652-a4d88400-2281-11ea-8b51-f0b20dfc369d.png)

Each of the tabs would contain the normal toolbar that allows to add, delete and hide spectra

We will have to check after how we deal exactly with the interactions

**Comment by hamed-musallam** [comment]
@lpatiny 
but what about grouping it as we done in panels.

**Comment by lpatiny** [comment]
You mean adding more panels ? I think there would be too many.
Other possibility that may be better is hierarchical list. Like in the example menu.

**Comment by hamed-musallam** [comment]
it will still hierarchical list.
