### ISSUE TITLE
toolbar small changes

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#245]
![image](https://user-images.githubusercontent.com/1484241/71195509-57164880-228e-11ea-8f0d-12481068cece.png)

Put full screen just under the zoom icon

Also for now hide the undo / redo icon (display: none)

**Comment by hamed-musallam** [comment]
@lpatiny 
i can't put the full screen button under zoom button because all the first 4 buttons are group button and has it own component and full screen button is normal one.

**Comment by hamed-musallam** [comment]
i hide the history buttons(redo and undo).
