### ISSUE TITLE
Add a big grey text when nothing is loaded

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#249]
If there is nothing loaded add a text

'Drag & drop here a Jcamp or NMRium file'

We will add more file formats later.

There could be some styling showing it is a drop zone like in this example

![image](https://user-images.githubusercontent.com/1484241/71240857-794dac00-230a-11ea-8cd2-b1bdad9600a3.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
where you need to display it, at molecular panel?

**Comment by lpatiny** [comment]
In the middle and in big instead of the spectrum (that is not present anyway)

**Comment by lpatiny** [comment]
Actually the scale could be hidden as well. We don't know anyway if it will be ppm or time.
