### ISSUE TITLE
no spectrum visible ... on firefox

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#25]
Is this normal ? I get the axes, but no spectrum on my screen this after:
npm i
npm start
<img width="796" alt="Screenshot 2019-07-06 10 55 35" src="https://user-images.githubusercontent.com/26463431/60754149-2e024400-9fdd-11e9-84b7-57d6a4325fce.png">

**Comment by lpatiny** [comment]
Are you using google Chrome ? It seems firefox currently does not work

**Comment by djeanner** [comment]
I was using Firefox indeed sorry!

On 6 Jul 2019, at 15:50, Luc Patiny <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using google Chrome ? It seems firefox currently does not work

**Comment by lpatiny** [comment]
@hamed-musallam 
In firefox the path is really generated but has a size of 4px
![image](https://user-images.githubusercontent.com/1484241/60759979-ba3c5780-a02d-11e9-93bf-3c47ef338c31.png)

**Comment by hamed-musallam** [comment]
i solved this problem it's related to something in how we build the path.

Close #25
