### ISSUE TITLE
Use react-table in Information

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#252]
Information panel should also use react-table

There could be the following improvements:
- Value should have fixed length font and preformatted (<pre>)
- If parameter name is too long we can limit with '...' using style 'ellipsis' css property: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
- There could be a visual info (background grey ?) to separate meta information from info information

**Comment by lpatiny** [comment]
Try the coffee. There is a crash if you click on the spectrum that is in the category NA

**Comment by hamed-musallam** [comment]
@lpatiny 
i know that, this because coffe7 does not contain nucleus.

**Comment by lpatiny** [comment]
Yes I saw this but it should still not crash. NA is perfectly ok

![image](https://user-images.githubusercontent.com/1484241/72078783-05dffe80-32fa-11ea-8f03-ee56a1fc86f2.png)

But clicking in this category should just show this spectrum

**Comment by lpatiny** [comment]
For solvent please apply the following regexp and make a dangerously html
```js
value=value.replace(/([0-9]+)/g,'<sub>$1<sub>');
```
