### ISSUE TITLE
Copy of data seems weird

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#255]
I don't find this part of the code really elegant

https://github.com/cheminfo/nmr-displayer/blob/10dd2d78051a3b5cb4be6e28f523bc46672a3c00/src/component/panels/RangesTablePanel.jsx#L48-L66

Is this really the best way to do ?

**Comment by targos** [comment]
is the goal to copy a subset of the values or everything?

you can do `return { ...range }` to create a copy of the full object

**Comment by lpatiny** [comment]
As far as I know it is not a selection but the full data. @hamed-musallam  Why there is this copy ?

**Comment by hamed-musallam** [comment]
@lpatiny 
this because we only get the ranges that belong to the active (selected) spectrum.
