### ISSUE TITLE
Required json format change

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#258]
We need to add a level to at least
- integrals
- ranges
- peaks

This level will contain:
- options
- values (the corresponding current array, integrals, ranges or peaks)

https://github.com/cheminfo/nmr-displayer/blob/9beafe7c2e235a351115c364b26b79d57a71da11/src/data/data1d/Datum1D.js#L321-L327

**Comment by hamed-musallam** [comment]
it's done

**Comment by lpatiny** [comment]
You could explain why we have a copy of ranges (_ranges) in the React Range Panel ?

**Comment by hamed-musallam** [comment]
@lpatiny 
can you point to code line?

**Comment by lpatiny** [comment]
Seems you removed https://github.com/cheminfo/nmr-displayer/blob/master/src/component/panels/RangesTablePanel.jsx#L47-L66
We have this _data (same in peaks)

**Comment by hamed-musallam** [comment]
@lpatiny 
https://github.com/cheminfo/nmr-displayer/issues/255#issuecomment-572498229
