### ISSUE TITLE
Feat: Display version number and date

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#259]
Could a version number and date of version could be written somewhere in the demo viewer?

![Screenshot 2020-01-09 at 15 32 08](https://user-images.githubusercontent.com/26463431/72076078-3cffe100-32f5-11ea-9eee-47d6994f4eb5.png)

**Comment by lpatiny** [comment]
Yes this is something to add when we will do release indeed.

**Comment by lpatiny** [comment]
I'm currently implementing a distribution workflow that allows to have 'released' version.

@hamed-musallam Please could you add next to NMRIUM either:
- the tag (if this is a tagged release)
- the beginning of the commit hash (like in github) in not tagged.
