### ISSUE TITLE
Simple way to create example

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#262]
Adding an import icon over the save icon:

![image](https://user-images.githubusercontent.com/1484241/72081007-02e70d00-32fe-11ea-8f5b-ed7b3033ec65.png)

One (and currently only) submenu will be:

- Add jcamp from URL

There should be a dialog box allowing to paste an absolute OR relative URL.

The full idea behind this feature is to easily create examples ...

**Comment by hamed-musallam** [comment]
@lpatiny 
we need to discuss further more in this feature, because i need to look how we can move the the selected jcamp file to public folder under specific folder.

**Comment by lpatiny** [comment]
The goal is not to save the resulting json file in the right folder. It is just to keep the jcampURL if it is available when creating the json file (saving).
It is easy for me to save (CTRL+S) and then take this json and move it in the data folder I want.
I need to create some examples with 2D spectra and this feature would really be useful.
