### ISSUE TITLE
When saving to json keep jcampURL

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#263]
When saving as a json file and if there is a jcampURL we should keep the jcampURL and not save the orignal neither meta information.

**Comment by lpatiny** [comment]
This is also true when we load an example. We should be able to save as JSON and replace the example json file without it adds the data in the json (in the original field). It should only keep the relative URL to the jcamp.

**Comment by hamed-musallam** [comment]
@lpatiny 
this issue also releated to issue #262.

**Comment by lpatiny** [comment]
duplicate #262
