### ISSUE TITLE
Add save as option

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#265]
Add a save as that allows to select the target folder but also setting the current default name (as in Save)

**Comment by hamed-musallam** [comment]
@lpatiny 
ok that's nice we can add save as, but can browse where to save the file ??

**Comment by lpatiny** [comment]
To be check. If there is no name the browser ask for one (and a path as far as I know). The question is to know if you can have a default name in this case.

**Comment by hamed-musallam** [comment]
@lpatiny 
After i do a sufficient search, i found that the only way is ti change the browser setting for example in chrome we need to change " Ask Where to Save ".
