### ISSUE TITLE
problem with spectrum size

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#266]
When we enlarge vertically/horizontally our browswer window, the 1D spectrum takes more space in it: no problem.
When we reduce the size horizontally, the spectrum reduces size, no problem.
When we reduce the size vertically, the spectrum keeps it size, and a scroll up/down apears - I think this is not desidred.

**Comment by lpatiny** [comment]
Which tool is selected ?
You can provide a picture ?

**Comment by djeanner** [comment]
No tool needed, just open a spectrum.
see movie https://www.dropbox.com/s/axr8cz88w3wcj7w/wind_prob.mov?dl=0

**Comment by hamed-musallam** [comment]
@lpatiny 
Actually the size of the container height has fixes value, at least 800 px.

**Comment by lpatiny** [comment]
Try to load the application on a small window. You can vertically increase the size but you will never be able to reduce the size. 

And it seems you may have a small vertical size

![image](https://user-images.githubusercontent.com/1484241/72235208-1f6e9800-35d1-11ea-8096-ba976f182592.png)
