### ISSUE TITLE
Signal analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#268]
@djeanner I wonder if you could help us to make a signal analysis algorithm that determine the multiplicity.

I remember there was an algorithm that considered that any signal is a 'dddddd' and then join the doublet in case the couplings are very close. Probably you know this paper (I would have to look for it).

Do you think you have the time to do implement such an algorithm ? This will be implemented in manual range picking.

If yes I would prepare a new project with some thereoretical test cases and a short explanation so that you can focus on the programming (without graphical interface).

**Comment by djeanner** [comment]
Yes, if you (indeed) prepare a ready-to-fill module/funtion... I will implement the multiplet deconvolution (my phd work) to extract couplings. In principle I only need an array of points corresponding to the multiplet (don't cut too close....you know truncation is bad... - maybe also send the full spectrum in case I want to cut the multiplet further...) as input and a way to know the resolution Hz/pt. I will need to apply trigonometric interpolation (similar to zero filling) ifft/add zeroes/fft to increase resolution and precision of the J's. So please also please include the needed modules (FFT, Ki square) and where the manual pages can be found. The function will return 1) the list of couplings (not the multiplicity - you will have to see if multiple couplings are identical) and 2) a the shape obtained after simplification of the doublets (a singlet - in principle) and 3) the reconstituted multiplet (by splitting according to the J's the results of deconvolution) which could be used to see if the deconvolution is satisfactory (may be Ky square). One difficulty will be to decide what to do with small couplings. Also prepare a test of the module with two examples - I need to be able to add my own input for additional tests (ascii or any format). I will also implement analysis of multiplets with antiphase (for COSY spectra...). Finally, please designate a person I could ask simple questions on JScript. I will be interested to know what other/existing functions are able to do - so please have the test calling the existing functions. This will allow me to evaluate if this approach makes sense.... Looking forward!
