### ISSUE TITLE
Create an example with 2D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#269]
Create 2D examples with cytisine:
- 1 HSQC
- 2 HMBC and 1 HSQC (superimposition)

**Comment by djeanner** [comment]
Maybe consider to display series of 1D spectra (diffusion / relaxation / temperature /titration) when the are in a two spectrum (2rr file). In this case the scale units will vary a lot - won't be ppm or Hz. Also consider J-resolved (no ppm in f1) and double quantum exp? both using Hz in F1.

**Comment by lpatiny** [comment]
You can now drag / drop a cosy (from ethylbenzene data folder) and it will be loaded correctly.

@hamed-musallam could you take care that in the list of spectra we show not only the datum1d but also the datum2d knowing that 2d we can do nothing with them ... But at least there will be the tab showing the 2 nucleus.

**Comment by nes-cgn** [comment]
There are now three sets of spectra (more or less simple) for completely characterized molecules at https://github.com/cheminfo/nmr-dataset1 (aspirin, ethylcrotonate and an aromatic amide). All containing 1H, HSQC and HMBC. I could create more
