### ISSUE TITLE
Reorganise components

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#271]
Reorganise all the react component to put everything that will work exclusively on 1D spectra in a folder called 1d

Rename ChartWindow.jsx to Chart1D.jsx

**Comment by lpatiny** [comment]
@hamed-musallam could you do this because Michael will start to work on the 2D component

**Comment by hamed-musallam** [comment]
@lpatiny 
ChartWindow we are not use it, i used it in the begining of project and it's wrap the nmr displayer in a window like windows window.
