### ISSUE TITLE
Create 2DChart component

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#272]
Based on the conrec output format be able to draw contours.

You may check the kind of output based on the test cases:

https://github.com/mljs/conrec/blob/master/src/__tests__/conrec.test.js

There should be 2 colors: one for positive and one for negative.

This new component should use D3 for calculations. You should check how it was done for the 1D.

Please make incremental commit so that we can comment quickly and efficiently.

**Comment by djeanner** [comment]
Instead of just two colors, why not have the possibility to define a color map or have a function returning the color code(sign,contour number)

**Comment by lpatiny** [comment]
Yes indeed a color per contour layer may be planned it will give more flexibility.
By the way the conrec algorithm returns closed contour which means that it is possible to fill each contour. This is also a feature we could use in the future.
