### ISSUE TITLE
Hiding all spectra does not work anymore

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#274]
How to reproduce ?

1. Select coffee example
2. Click on the hide all button

![image](https://user-images.githubusercontent.com/1484241/72222762-ad626880-3568-11ea-87b9-4b3ad1417c91.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
what happens right now, if you click at any tab it will show all spectrums in that tab, and if you click to hide all spectrums it will hide all spectrums. so what is the point that refers to?

**Comment by lpatiny** [comment]
I can not reproduce this problem. I was maybe not using the last version sorry. It works perfectly.
