### ISSUE TITLE
what is the best pattern and strategy to seprate the business logic from the ui elements

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#28]
what about  using Redux  because it's implement a lot of features that we can used it for example redo and undo states and share data between components,
also what is the best pattern and strategy to seprate the business logic from the ui elements.
@targos 
@lpatiny

**Comment by lpatiny** [comment]
There is no need to use redux. For state management in React the hooks should be enough (useState, useReducer and useContext).

You should create a hook that uses the processing library and that allows to get the latest chart with all the annotations (of all the kinds).

```jsx
class Spectrum1D {

  peakPicking() {
    
  };
}

// The ReactNMR component will use chartDispatch to send the events for peak picking, base line correction, etc
function NMR() {
  const [chart, chartDispatch] = useChart(); 
  return <ReactNMR chart={} chartDispatch={} />
}
```
