### ISSUE TITLE
samples.json could come from anywhere

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#282]
In order to make different kind of exercises we should plan different layouts but also different source of the samples.json file.

The current home page should allow a URL parameter 'toc=urlToSample.json' that would be used to display the exercises.

In the samples.json the jcampURL will be relative to the samples.json URL.

**Comment by hamed-musallam** [comment]
@lpatiny 
as far as i know how the route works in react js and even in any other library, this route for specifc view or page and the samples.js this the main reference that generate those routes, so how to pass the json file that contain the routes  in the same url that generated from samples.json !!!!!

**Comment by hamed-musallam** [comment]
@lpatiny 
Now By default when you run the app directly will loaded from the local samples files.
you can load from external samples files by enter the sampleURL for that file for example
/Main?sampleURL="<your url>".
