### ISSUE TITLE
Advanced shortcut to save / load 'views'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#285]
Using numbers 1 to 9 we should save what is currently displayed on the screen and reload those preferences

This includes:
- the spectra currently displayed (color, show / hide peaks, visible yes / no)
- vertical scale, horizontal scale

Behaviour: 
- If you press a number and it was not yet assigned the system should associate the current preferences to this number.
- If you press a number and it was assigned the preferences are reloaded (this may include showing 1H instead of 13C)
- If you press SHIFT + number we always associate the current preferences to this number

I guess this should be a special component

**Comment by hamed-musallam** [comment]
@lpatiny 
we are going to save these preferences per browser in  the browser local storage, is that what you want?

**Comment by lpatiny** [comment]
Only for the current display in fact. Nothing stored in localstorage. Each time we reload some spectra we clear those preferences.
It would be nice that it corresponds to a set of spectra and also a specific nucleus so that you can quickly go from a set of 1H spectra to a set of 13C spectra.

**Comment by lpatiny** [comment]
@hamed-musallam please add a feedback when the parameters are saved
