### ISSUE TITLE
Change nucleus and displayed spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#289]
When changing of nucleus panel we should remember the last displayed spectra for this nucleus.

![image](https://user-images.githubusercontent.com/1484241/72431190-85efe380-3794-11ea-98d7-fa1290658af9.png)

If there was nothing we should display all the spectra concerning this nucleus.

The display (X axis) should be adapted for the current nucleus (related to #261)

**Comment by hamed-musallam** [comment]
@lpatiny 
for the current stage we can't do it, because we group the spectrums logically, so when we select one of tab we look in the spectrums array for spectrums that   mached or have the same nuclues as the selected tab and then we show these specreums and hide the others
