### ISSUE TITLE
Peaks panel preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#293]
We should be able to show / hide the following columns:

- Peak number
- Peak index
- Chemical shift (delta (ppm))
- Chemical shift (delta (Hz)) (= chemical shift ppm * spectrum frequency)
- Peak width
- Intensity

By default:
 - Chemical shift
- Peak width
- Intensity

Each field could have a default formatting preference so that we have an idea of the format.

For now peakWidth will only be available for auto peak picking.

**Comment by hamed-musallam** [comment]
@lpatiny
What do you mean in peak width and how it's related to auto peak picking, Also is the chemical shift can be  visible in ppm and in the same time in hz?

**Comment by lpatiny** [comment]
Peak width is calculated by the auto peak picking. I added this property in the peaks. It is the widht of the peak half-height.
Yes the chemical shift could be seen in ppm and hz.
