### ISSUE TITLE
Full zoom out 'ff'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#294]
For the full zoom out we should act already on the first 'f' pressed, meaning make the horizontal full out zoom.

If the 'f' is pressed again during the next second we will make the vertical full out as well.

Currently it seems there is aways this 1s delay that does not feel that nice.

**Comment by hamed-musallam** [comment]
@lpatiny
but what implement right now is that if double click in full zoom out button or f, it will zoom out vertically and horizontally and if you press one time it will zoom out horizontal

**Comment by lpatiny** [comment]
It is just that when you press 'f' it seems there is a delay (waiting to check if there is a second 'f' ?) before actually do the horizontal zoom out. So it is not immediate as before.

**Comment by hamed-musallam** [comment]
@lpatiny 
Yes i delay for 500 milliseconds to check if it's one click or double click, but you suggest to perform zoom out horizontal from the first click  and zoom out  vertically and horizontally if second click come.
is that what you suggest?

**Comment by lpatiny** [comment]
Exactly
