### ISSUE TITLE
Preferences for integrals

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#298]
In the integral panel we should add preferences:

* show / hide value
* show / hide relative, and allow formating of relatvie integral .Default: 1 decimal

Title of the column for relative integral is:
nb + nucleus (in fact nucleus.replace(/[0-9]/g,'')

So for example if nucleus is `1H` the title of the column will be `nb H`

**Comment by lpatiny** [comment]
While the options to display column are selected

![image](https://user-images.githubusercontent.com/1484241/72977312-8dd30780-3dd4-11ea-8079-690ac10b5ce2.png)

The columns don't appear

![image](https://user-images.githubusercontent.com/1484241/72977283-7c89fb00-3dd4-11ea-8a23-b78ed58c7321.png)

**Comment by hamed-musallam** [comment]
@lpatiny
that's because the json file does not contain these preferences for the integral, but if you save as json and drag and drop the file into blank template it will work.

According to that what you suggest?

**Comment by lpatiny** [comment]
I think it will happen that we constructthe json by hand (to convert from nmredata or bruker file for example) and we don't put all the 'required' properties.

So it make sense that if those preferences do not exists there is a default preference that is injected.

I would suggest to add a method that checks and add the missing properties when loading the json.
