### ISSUE TITLE
Add small icon for FID or spectrum in list of spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#300]
Display in list of spectra if FID or FT

**Comment by hamed-musallam** [comment]
@lpatiny 
What is the suggested icon for both FID and FT?

**Comment by lpatiny** [comment]
I just added 2 icons in our cheminfo-font package (you need to pull and make `npm i`)

![image](https://user-images.githubusercontent.com/1484241/72985800-0cd13b80-3de7-11ea-9d2a-0645bc2d724b.png)

- nmr-ft
- nmr-fid
