### ISSUE TITLE
Importing Bruker files

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#302]
One main concern will be, that most users come with manufacturer's proprietary software files. And Bruker occupies an almost monopoly currently. So, even for our Praktikum here, it is necessary to import TopSpin files (people will not convert to jcamp first). Also, for the general acceptance of the displayer this is going to be very important

**Comment by lpatiny** [comment]
At list in some industry they send automatically the jcamp at the end of the run. This is simply a checkbox in iconNMR so pretty standard. Much easier also to attach in lab notebook. Only one file to attach.

**Comment by jwist** [comment]
As Luc mentioned jcamp is standard on all spectrometer and can be done
within a single command. Now we are able to read bruker format as well, the
thing is that it is a folder and for web application it means that the
folder has to be compacted into a zip file. So currently the user have both
options, either submit a zip file of the bruker folder or a jcamp.

Director de la Oficina de Transferencia
de Resultados de Investigación -OTRI
Dr.Sc. Assistant Professor (Chemistry Department)
Universidad del Valle, Cali, Colombia
website: http://www.cheminfo.org


*AVISO LEGAL:* Este mensaje y/o sus anexos son confidenciales y para uso
exclusivo de su destinatario intencional. Si usted no es el destinatario,
le informamos que no podrá usar, retener, imprimir, copiar, distribuir o
hacer público su contenido. Cualquier retención, revisión no autorizada,
distribución, divulgación, reenvío, copia, impresión, reproducción o uso
indebido de este mensaje y/o anexos, está estrictamente prohibida y
sancionada de acuerdo con la Ley 1273 de enero del 2009. Si ha recibido
este correo por error, por favor elimínelo e infórmenos al correo
xxxxxx@correounivalle.edu.co Si usted es el destinatario, le solicitamos
mantener reserva sobre el contenido, los datos o información de contacto
del remitente y en general sobre la información de este documento y/o
archivos adjuntos, a no ser que exista una autorización explícita.

**Comment by nes-cgn** [comment]
So, that is interesting - a zipped folder from Bruker can be read. This would actually help as an interim solution. I know quite a number of German NMR labs, none of them producing jcamp unfortunately, and if we want to attract their interest in the use of the application, a previous change of their workflow will not really convince them. The Bruker files really need to be readable [just to make the point clear: for me, a standard format is definitively preferable, but this switching process will take some time]. Wouldn't it be possible to implement the zip file option?

**Comment by steinbeck** [comment]
I agree that for a wide spread adoption, also for our purposes, working with original Bruker files will be beneficial, if not necessary. 
I would not have thought 20 years ago that I would ever make such a statement :)

Kind regards, Chris

**Comment by djeanner** [comment]
I would like to be involved in this because because I work a lot with chemistra data/meta data for sharing, etc. If the reader/converter is good, it can be very usefull also as a way to make them more findable. I means efforts should be made to get the date of acquisition, the type of instrument, (probe can help..), softeare version, etc. Where the file was stored initially is also good to take even if it is oftern "nmr", when it is not, it may point to the research group who made the analysis, something I could convince you to be VERY interesting to put spectra and molecules together at a later stage... I have a very nice collection of Bruker acqus files to test readers...

**Comment by nes-cgn** [comment]
Currently, the import of .zip directories from Bruker data works, but only for directories that contain >=2 subdirectories. I guess, it should not be difficult to change that. The typical structure is [experiment folder]->[subdirectory with numbered experiment folders like 1, 2, 3 etc.]->acquisition information files (acqu, acqus, audita.txt, fid, uxnmr.par etc..) plus [subdirectory with processing information]->[1]->processing information (auditp.txt, outd, proc, procs etc.). At the moment, in the processing subdirectory [1], there need to be the 1r and 1i files (which should not be).

**Comment by lpatiny** [comment]
I did drag / drop a zip of bruker files and it currently works. Please open a new ticket with a zip that does not work in case you encounter problems.

**Comment by nes-cgn** [comment]
Seems that there are problems again, none of the following files could be imported by me, nor others that I tried

[Displayer_50-78-2.zip](https://github.com/cheminfo/nmr-displayer/files/5437033/Displayer_50-78-2.zip)
[example-1-1h (2).zip](https://github.com/cheminfo/nmr-displayer/files/5437034/example-1-1h.2.zip)
[example-1-1h.zip](https://github.com/cheminfo/nmr-displayer/files/5437035/example-1-1h.zip)
[141-32-2.zip](https://github.com/cheminfo/nmr-displayer/files/5437036/141-32-2.zip)
[CSE.zip](https://github.com/cheminfo/nmr-displayer/files/5437037/CSE.zip)

**Comment by hamed-musallam** [comment]
it's done
