### ISSUE TITLE
Resetting blank area for import

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#303]
For the students (and others) that are going to test, it would be useful if there were a button or icon to reset/blank the drag&drop area for a new start. Currently, I can only find the option to reload the page for the blank area or switch in between to the example spectra section

**Comment by lpatiny** [comment]
Today you can also click on the 'trash' icon in the list of spectra

![image](https://user-images.githubusercontent.com/1484241/73010173-32276f00-3e12-11ea-947f-05aa8c9cc6f9.png)

But indeed we could reload the page. @hamed-musallam how difficult it is to be allowed to click again (and reload) the page that is currently active. So if you click on blank while you are on blank it reloads the page.
