### ISSUE TITLE
simplify data struture

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#306]
Currently in the JSON and internally we have data1d and data2d.

![image](https://user-images.githubusercontent.com/1484241/73596399-2dee0680-4522-11ea-9325-cef88e984bcf.png)

This makes things quite complex in order to display the list of spectra but also in order to parse jcamp that may contain 1D and 2D (in the same jcamp).

We should have only ONE array containing all the data called `spectra` 

@hamed-musallam Please could you do this refactoring and the change of all the examples ? (actually it will just be replace 'data1d' by 'spectra'

I will then improve the loading of spectra to deal with 'linked' jcamp.

**Comment by lpatiny** [comment]
This is also the case in the source code and 'Analysis' object where data1d and data2d disappear to keep only 'spectra'. I would also rename the field 'data' to `spectra` in contrast with `molecules`

**Comment by hamed-musallam** [comment]
@lpatiny 
it's not prefer to rename data to spectra because for now the first level will be like
{
spectra:{ spectra:{ it's not make sense}
}
molecule:{}
}
and we relay on the data prop name in every corner in reducer.js
