### ISSUE TITLE
Deal correctly with FT / FID mixed spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#309]
In some cases we have various 1D spectra, some of the FT and some of them FID.

For exemple if we load 5 FID and we make the FT of one of them.

Currently it is problematic because both spectra are displayed leading to some weird superimposition. The xAxis unit is also obviously wrong for one of the spectra.

If one spectrum is selected all the visible spectra of the same kind (FT or FID) should be displayed and the xAxis unit changed if necessary.

If no spectrum is selected and there are some visible FT we should display only the FT.

**Comment by hamed-musallam** [comment]
done
