### ISSUE TITLE
capture events in Exercise view

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#312]
Even if we are over the OCL editor when we press 1 the event is capture by the nmr-displayer. Events for the nmr-displayer (key shortcuts) should only be cached when we are over the nmr-displayer

**Comment by hamed-musallam** [comment]
@lpatiny 
I'm not sure if we can listen to the key-down events on displayer without making the displayer focused, because if focus out we can't capture the key down events.

right now we listen to  key-down  on the document object

**Comment by lpatiny** [comment]
The problem is that openchemlib use similar shortcuts and therefore we have a conflict. I think the keydown listener should check that the mouse if over the nmr-displayer.
