### ISSUE TITLE
Add grey banner information in the bottom

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#313]
This banner will contain for now:
- x position in ppm
- x position in Hz
- y (intensity)

I guess it will evolve in the future and we will display more information in it

**Comment by lpatiny** [comment]
Looks great thanks !

Please update this line with the currentSpectrum frequency

https://github.com/cheminfo/nmr-displayer/blob/33d6b2bb2ace24394af97dda76466b6793eb3881/src/component/1d/FooterBanner.jsx#L60

**Comment by hamed-musallam** [comment]
done
