### ISSUE TITLE
Display parameter used for digital filtering

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#317]
Currently this filter appears without parameter

![image](https://user-images.githubusercontent.com/1484241/73965690-e77b1c00-4914-11ea-8f55-328eb27b6224.png)

We need to show the value used because there is a bug that is difficult to check without this information.

**Comment by hamed-musallam** [comment]
@lpatiny 
I do not pass any parameters to Digital filters.
