### ISSUE TITLE
Delete all spectra crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#318]
If you load a spectrum and then delete it from the list of spectra (trash icon)

![image](https://user-images.githubusercontent.com/1484241/73968181-87d33f80-4919-11ea-9100-f3988e34698b.png)

You get an error

![image](https://user-images.githubusercontent.com/1484241/73968089-68d4ad80-4919-11ea-8012-47bfc31cab79.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
may be I broke some methods during the refactoring, I will check it from the morning.
