### ISSUE TITLE
Digital filter not applied if no zero filling

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#319]
If you drag and drop an FID (see attachment) and make the FT directly you get a huge phase problem

![image](https://user-images.githubusercontent.com/1484241/73968287-bd782880-4919-11ea-81e4-e0eb994e777f.png)

While if you first make a zero filling and the FT it looks ok

![image](https://user-images.githubusercontent.com/1484241/73968365-de407e00-4919-11ea-8d75-01e86cbe4283.png)

The digital filter should be applied when loading the spectrum and I don't know where it is currently applied.

[1h.dx.zip](https://github.com/cheminfo/nmr-displayer/files/4167174/1h.dx.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 
we apply the  Digital Filter when we load the spectrum inside the datum1D contractor.

**Comment by lpatiny** [comment]
@nes-cgn Do you think this is normal to have this wobbling baseline ? Could you try to use this jcamp with and without zero filling maybe with Topspin to check if you have similar results ?
In the code it looks like we apply the digitalFilter correctly.

**Comment by nes-cgn** [comment]
Hello, I took the FID and did an FT without zero filling and without exponential appodisation, result without phasing
![1H_after_ft_no_zerofill](https://user-images.githubusercontent.com/47237343/75318492-ce59f100-586a-11ea-859c-29b8de95120d.PNG)

**Comment by nes-cgn** [comment]
Then I did the same with zero filling and with 0.3 Hz linebroadening (see below)
![1H_after_ef](https://user-images.githubusercontent.com/47237343/75318537-f21d3700-586a-11ea-82ae-ab8c9eeed1fb.PNG)

**Comment by nes-cgn** [comment]
The phasing that I need to apply is quite humble
![1H_after_ef+pcorr](https://user-images.githubusercontent.com/47237343/75318564-0103e980-586b-11ea-84f2-149bc0cc9f26.PNG)
![1H_after_ef+pcorr_par](https://user-images.githubusercontent.com/47237343/75318570-03664380-586b-11ea-8458-9c0f0c604fac.PNG)

**Comment by lpatiny** [comment]
@nes-cgn Could you vertical scale your spectrum because in our case Y axis is really scaled in order to see those defects.

**Comment by jobo322** [comment]
I think we should apply the digital filter just before FFT filter because if we apply digital filter before zero filling we will get a wrong behavior

**Comment by jwist** [comment]
This was mainly an issue with the digital filter. It is now mostly solved for recent files (with grpdly > 0)
