### ISSUE TITLE
Simple backend using GraphQL

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#33]
* Drag / drop a jcamp -> saved on the HD
* Save / load assignment
* List existing spectra

`npm start server` : starts a local graphQL server that stores on the hardisk

* /data/uuid : a folder containing sample
* /data/uuid/index.json : sample information
* /data/uuid/spectra/nmr/md5/ md5 of the jcamp file
* /data/uuid/spectra/nmr/md5/index.json filename, peaks, integrals, ...
* /data/uuid/spectra/nmr/md5/jcamp.jdx

**Comment by lpatiny** [comment]
@targos  We would need somehow a backend that allows to store demo spectra as well as to test the assignment, filters, peaks, etc as well as storage of all the data.

What do you think ? Does it make sense to create a graphQL server that would store for the demo on the harddisk and later to a database ?

**Comment by targos** [comment]
If you want to simulate a backend, it seems easier to me to use IndexedDB

**Comment by lpatiny** [comment]
Currently not required
