### ISSUE TITLE
Phase correction should be done on reduced data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#331]
Current phase correction is rather slow.

The calculation should be done on reduced data (so reduced real and imaginary).

Don't know how to deal with this because we should take care that the user may zoom to a specific place.

Only when the PH0 and PH1 are defined it is applied on the full spectrum.

**Comment by lpatiny** [comment]
In order to reduce the data we should use:
```
import equallySpaced from 'ml-array-xy-equally-spaced';

      let reduced = equallySpaced(
          { x, y: re },
          { numberOfPoints: 4096, zones },
        );
```

**Comment by hamed-musallam** [comment]
@lpatiny 
Can we apply the reducer in filter itself?

**Comment by lpatiny** [comment]
It is a temporary reduction of data size during the interactive phase correction.
