### ISSUE TITLE
Vertical scale of integral very slow

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#334]
React plugin in the browser show that when you vertical scale the integral the Panels are redraw.

I see different problems here:
1. All the panels are redraw and we touch only the integral
2. Even the integral panel is redraw while it should not be. Vertical scaling is not displayed in the integral panel and changes nothing to the values.

Please identify why it is redraw and fix the origin of the problem.

**Comment by hamed-musallam** [comment]
@lpatiny 
because we calculate the integral right before we display it. 
https://github.com/cheminfo/nmr-displayer/blob/ecf517ab58d4215ed4926d5cba428d28ca39cfb1/src/component/1d/IntegralsSeries.jsx#L41-L59

**Comment by lpatiny** [comment]
If we only change the vertical scale the integral should not be recalculated. 

It should be recalculate if from/to change of the spectrum change (phase correction, baseline correction)
