### ISSUE TITLE
Baseline correction not working

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#335]
Nearly all the code is now implemented to make baseline correction. There are 2 algorithms: airPLS and polynomial.

The default should be 'polynomial'.

If no zones are defined an algorithm will that only works with 'positive' peaks will be applied.

What is currently wrong ?
1. Default algorithm not 'polynomial'
2. The code is executed many times

@hamed-musallam Could you have a look on this ?

**Comment by hamed-musallam** [comment]
@lpatiny 
i tested the code and the code does not execute many times, Can you give what the case because i need to simulate it.
