### ISSUE TITLE
Range picking modification manual assignment

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#341]
- [x] Allow to SHIFT + click / drag / release to select a range like when adding an integral
- [x] Allow to ALT + click / drag / release : same as before + open a debug window
- [x] When range is selected call: Datum1D.addRange

**Comment by hamed-musallam** [comment]
@lpatiny 
Is the second point connected to  #342 ? can you give me the normal path for the process.

**Comment by lpatiny** [comment]
Yes it is connected to  #342.

**Comment by lpatiny** [comment]
Seems to me there is a bug in multiplet-analysis package and we need to wait it is fixed: https://github.com/cheminfo/multiplet-analysis/issues/16

**Comment by lpatiny** [comment]
I have added the last version of the multiplet-analysis and also an option to detect where is the peak.

It crash less often at least

@hamed-musallam 
- [ ] Please check the code and add the range. I just create the range object but even do not return it.
- [ ] Try / catch the call to addRange and if there is an error give a visual feed-back to the user

**Comment by hamed-musallam** [comment]
@lpatiny 
ok i will check it tomorrow.
