### ISSUE TITLE
Multiplet analysis debug window

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#342]
Provide a dialog box displaying the debug information of the multiplet analysis.

The content of the dialog box look like: 

https://cheminfo.github.io/multiplet-analysis/

This multiplet debug dialog box will receive a json like: https://raw.githubusercontent.com/cheminfo/multiplet-analysis/master/examples/web/result.json

It is converted the webpage using this index.html file:

https://github.com/cheminfo/multiplet-analysis/blob/master/examples/web/index.html

The goal here is to be native and to use the react-jsgraph component from: https://github.com/zakodium/react-jsgraph

**Comment by lpatiny** [comment]
@hamed-musallam In order to get the debug information you should add 'debug: true' in:

https://github.com/cheminfo/nmr-displayer/blob/cc79b92dc7a7d426afb2924839f3d22ae8e6d501/src/data/data1d/Datum1D.js#L360-L363

**Comment by lpatiny** [comment]
@djeanner also asked that we could copy the data like in the case of crash. This could be done here as well. You copy the data in the clipboard and you display the debug information in a dialog box.

**Comment by lpatiny** [comment]
@hamed-musallam did you copy the data to the clipboard as well when you press ALT ?

**Comment by lpatiny** [comment]
Another way that may even be better is to make a right click on the multiplet table and 'Copy data to clipboard' that copies the (x:[], y:[]} from/to area to the clipboard

**Comment by hamed-musallam** [comment]
@lpatiny 
No i did not copy the data when i show the multiplet window. Do you want to copy the data also to clipboard when open the window.

**Comment by lpatiny** [comment]
i wold prefer the contextual menu on the multiplet panel to copy the data. _this would be very practical for debug.

**Comment by hamed-musallam** [comment]
@lpatiny 
did you want to copy all the data in the table or only row by row? if all data do you want do it like what we did in structure panel 
![image](https://user-images.githubusercontent.com/35760236/75867690-44300080-5e07-11ea-851f-acc407479d27.png)

**Comment by lpatiny** [comment]
In this case it is row by row, It should be 'copy range data' and in the clipboard we should put a string {x: [], y:[]} will all the values of the points corresponding to the range. (not the reduced data but the original one)

**Comment by lpatiny** [comment]
We also need in the clipboard the x / y data. Please add a property data: {x:[], y:[]} that contains all the points from this range (the points from the original data).
