### ISSUE TITLE
Improve Ranges accordion display

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#345]

**Comment by nes-cgn** [comment]
I tried the ranges function, and if I attempt to define several, overlapping regions (which is possible in the interactive mode), they are finally (after pressing the "apply" icon) merged into one range. For my understanding, this is not ideal, if one e.g. defines multiplets in a highly overlapping area. Instead, individual regions should be kept

**Comment by lpatiny** [comment]
@nes-cgn this is not related to this ticket. Please open a new one.

**Comment by lpatiny** [comment]
@hamed-musallam please improve the layout

![image](https://user-images.githubusercontent.com/1484241/77854494-026a5e00-71eb-11ea-9dc7-3f74ea541d36.png)

In the #Signals column we should need a join of the multiplicity of all the signals

Something like 2: dd, dt.  (2 signals, one dd and one dt)
