### ISSUE TITLE
missing specral processing option when loading a jcamp spectrum

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#351]
I opened this [jcamp spectrum](https://www.dropbox.com/s/0wv54wfaha6tcan/dj_ge425.jdx?dl=0)(export from mnova) but coudl not use the multiplet analysis buttons. 
![Screenshot 2020-02-25 10 07 26](https://user-images.githubusercontent.com/26463431/75232098-e7a16580-57b6-11ea-8a25-864e893c76fb.png)

**Comment by lpatiny** [comment]
You need to select the spectrum so that the menu appears

![image](https://user-images.githubusercontent.com/1484241/75233936-f6d5e280-57b9-11ea-8ba2-49658fa412a1.png)

Not sure if this should be the default behaviour and we should discuss about it.

**Comment by lpatiny** [comment]
I attach the file in the ticket (>as ZIP).

[dj_GE425.jdx.zip](https://github.com/cheminfo/nmr-displayer/files/4249163/dj_GE425.jdx.zip)

**Comment by lpatiny** [comment]
@hamed-musallam can you try to drag / drop this unzipped file on an empty view because I get the error

![image](https://user-images.githubusercontent.com/1484241/77853457-7d7c4600-71e4-11ea-8e15-79ae1013dff7.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
I tried to load the jdx file couple of times and did not get an errors.

**Comment by lpatiny** [comment]
Current is seems to work.
