### ISSUE TITLE
Check hsqc / hmbc example

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#362]
I added an exemple of hsqc / hmbc and it should be checked if it is loading (very slow in all the cases)

**Comment by hamed-musallam** [comment]
@lpatiny 
for me it seem that it's slow because drawContour took time to complete and this happen when we load or  even zoom it's freeze the whole application until the result returned.

**Comment by lpatiny** [comment]
The problem is not the speed (we will improve it once) but the display. It works now thanks !
