### ISSUE TITLE
Coffee example not loading

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#363]
I know that there is one of the spectrum that does not have nucleus but still I think they should be loaded.

Currently only one spectrum is visible.

@hamed-musallam please could you have a look ?

**Comment by hamed-musallam** [comment]
@lpatiny 
I track the problem and i found that it come from 
https://github.com/cheminfo/nmr-displayer/blob/b31abea58a47bce65653047c51ced4b21b514ee4/src/data/SpectraManager.js#L50-L59

in the info object  we get dimension value 0 and it's not match any condition.

![image](https://user-images.githubusercontent.com/35760236/77888148-130ee880-726c-11ea-9017-df6ffde70c5d.png)
