### ISSUE TITLE
Rename relative / integral in range

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#366]
Currently we have

https://github.com/cheminfo/nmr-displayer/blob/b31abea58a47bce65653047c51ced4b21b514ee4/src/component/panels/RangesTablePanel.jsx#L191-L200

This should be renamed:
* range.integral -> range.absolute
* range.relative -> range.integral

This should be done everywhere, also in Datum1D

**Comment by hamed-musallam** [comment]
@lpatiny 
only rename the variable names.

**Comment by lpatiny** [comment]
range.absolute will contain the value that is currently in range.integral
range.integral will contain the value that is currently in range.relative
