### ISSUE TITLE
Bruker zip files that still do not work

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#367]
The following zip directories still do not work well - the one called AV499 is produced on an Avance III HD under Topspin 3, including an automated processing after recording, done in magnitude mode (we use in 3 spectrometers an automated S/N determination). It can be imported and is visualized (good!) but one would need to to another FT of the FID (only the mc mode processing is otherwise available). The second example is from an older Avance III spectrometer (AV500) which also runs under Topspin 3. Here, the file is not visualized. I put one with only 1H and another one containing 1H and 13C.
[AV500-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4399675/AV500-1H.zip)
[AV500-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4399676/AV500-1H-13C.zip)
[AV499-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4399677/AV499-1H.zip)

**Comment by nes-cgn** [comment]
Hello, here are some more files that do not work for us. I put as in the example file from Julien some that contain two experiments (the ones that are labelled 1H-13C).
[50-78-2-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4402163/50-78-2-1H.zip)
[50-78-2-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4402164/50-78-2-1H-13C.zip)
[86-55-5-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4402167/86-55-5-1H.zip)
[86-55-5-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4402169/86-55-5-1H-13C.zip)
[91-64-5-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4402170/91-64-5-1H.zip)
[91-64-5-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4402171/91-64-5-1H-13C.zip)
[140-67-0-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4402172/140-67-0-1H.zip)
[140-67-0-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4402173/140-67-0-1H-13C.zip)
[141-32-2-1H.zip](https://github.com/cheminfo/nmr-displayer/files/4402174/141-32-2-1H.zip)
[141-32-2-1H-13C.zip](https://github.com/cheminfo/nmr-displayer/files/4402175/141-32-2-1H-13C.zip)

**Comment by lpatiny** [comment]
Currently we only display bruker file if they contain 1r and 1i. There is no process data in the file

**Comment by nes-cgn** [comment]
Ok, I see. But since a fundamental part of the project is that people do the FT and phase correction, it will be important to also allow non-processed data to be imported. All of our spectra are transferred as unprocessed raw data, nobody could do any beta testing so far.

**Comment by jliermann** [comment]
> Currently we only display bruker file if they contain 1r and 1i. There is no process data in the zip

So it's not a bug but a limitation for the time being. I think this issue should be replaced by a feature request then?

**Comment by nes-cgn** [comment]
Here is the last E-Mail that I received from Kirk Marat on the topic:

Just thought I would send along some pointers on the format of Bruker 1D data.  If you guys are already aware of these things, please accept my apologies for bothering you.

Probably the best way to have the users select data is to drag the experiment number folder to the application.  The experiment number folder contains all of the files for the data.  Internally, you can then easily generate the paths to the required files.  You will need the acqus and fid files from the experiment number folder and then the proc and possibly the procs files from the pdata/1 folder, assuming that the processed data folder is 1 (usually is for most experiments).  Optionally, you may also want to read the title file - the users usually like this.  Whether you use the procs parameters or not depends on whether you want to use phasing and referencing parameters that were determined by processing in TopSpin.

After reading all the necessary parameters, you will then have to read the fid.  First you will need to look at the DTYPA parameter (acqus file) which will tell you whether the data are 32 bit integer (DTYPA = 0, most common) or 64 bit floating point (DTYPA = 2, rare).  I think 32 bit floating point is also possible (DTYPA = 1) but I haven't seen any.

You will then need to check the byte order of the data from the BYTORDA parameter (acqus file), with 0 being LITTLENDIAN and 1 being BIGENDIAN.  Most newer Bruker will likely be LITTLE.  How the byte ordering is handled depends on the programming language that you are using.  C derived languages require an en explicit byte reversal in some cases to match the processor order, while Java can do this implicitly at the read time by specifying the ordering of the data.  You can see the difference by comparing the C# vs. the Java versions of SpinWorks.  Note that while the Intel processors have LITTLE ordering, the Java virtual machine (JVM) has BIG byte ordering.  Sun Sparc and SGI are also BIG.  Once the data type and byte ordering are known, a simple binary read can be used for the fid file.  There is no file header or block header as found in Varian/Agilent data.

I hope that this information is useful.  If so, I can pass along some tips on reading 2D files.

**Comment by jobo322** [comment]
Hello @nes-cgn, I did changes in the project to read raw data from a Bruker zip file. Currently, I'm having problems reading your FID older files

50-78-2-1H.zip
50-78-2-1H-13C.zip
86-55-5-1H.zip
86-55-5-1H-13C.zip
91-64-5-1H.zip
91-64-5-1H-13C.zip
140-67-0-1H.zip
140-67-0-1H-13C.zip
141-32-2-1H.zip
141-32-2-1H-13C.zip

**Comment by nes-cgn** [comment]
Thank you, looking forward to this. Currently, I tried with (zipped) files from three of our standard instruments (two of them running TopSpin3.5/6, one with Topspin2.1). I cannot read any of them on the present version. If it helps, I can send you the files

**Comment by jobo322** [comment]
Hello @nes-cgn, could you try again, we did some changes

**Comment by nes-cgn** [comment]
Good morning,

that is absolutely amazing!!! Thank you VERY much - I did a testing  
with files from all of our spectrometers from last week and it did not  
fail a single time. This is really a great news, because then we can  
spread the news and have finally students test the performance.

Thank you very much for your efforts, and I am esp. thankful since  
this is the only good news in a really tough time for me at the moment,

kind regards,
Nils


Zitat von Jose Alejandro Bolanos Arroyave <notifications@github.com>:

> Hello @nes-cgn, could you try again, we did some changes

**Comment by nes-cgn** [comment]
Thank you very much! It works really great now - I really appreciate this, it is for the practical application a big step forward
