### ISSUE TITLE
Allow superimposition of 2D spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#369]
If we display the 2D mode we will not have more than 1D trace on top or on the left.

However we may want to display more than one 2D spectrum like in the example HSQC / HMBC.

This should be the default behaviour if no 2D is selected. We should also be able to decide the color of each of the spectra.

**Comment by hamed-musallam** [comment]
do you mean display more than one 2d at once, or display the active spectrum ?  you know already that the 2d spectrum contain negative and positive signals so the question for which signal the selected color will be and how you imagine we will decide the color for the other signal

**Comment by lpatiny** [comment]
We allow superimposition of many 2D spectra of the same kind like hsqc / hmbc example. Each 2D has his own color (positive and negative)
