### ISSUE TITLE
Peak picking not working 

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#37]
I think that the peak picking is not working anymore... since multiple spectra view?

**Comment by lpatiny** [comment]
Did you select a spectrum ? you need to select a spectrum by clicking on the thin line next to the spectrum on the right.

you should have seen a message telling you this:

![image](https://user-images.githubusercontent.com/1484241/61944604-5fe44600-af9e-11e9-9b79-b109c33357ea.png)
