### ISSUE TITLE
Zoon on 1D traces not correct in 2D display mode

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#371]
When zooming in the 1D trace of a 2D there should be a zoom only in one of the direction and not the 2.

Currently if you zoom on a 1D trace the 2D disappear (out of range I guess).

**Comment by hamed-musallam** [comment]
@lpatiny 
in 2d displayer you only have the ability to zoom in 2d area and you can't zoom the top or left 1d  a lone.

**Comment by hamed-musallam** [comment]
it's done
