### ISSUE TITLE
JCAMP of 1H created in Mnova 14.1.2 will not load

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmr-displayer#372]
- When I upload a JCAMP of an 1H generated in Mnova, nothing happens (two examples attached).

Testing done by me:
- JCAMP files of 13C generated by Mnova work (attachment, suffix _13c_mnova)
- JCAMP files generated by TopSpin of the same spectra work (attachment, suffix _bruker)
- JCAMP files converted by TopSpin from the Mnova JCAMPs work (attachment, suffix _mtob)

[examples.zip](https://github.com/cheminfo/nmr-displayer/files/4420714/examples.zip)

**Comment by lpatiny** [comment]
I don't see the files. Can you zip them and upload them here ?
