### ISSUE TITLE
add shortcut for menu items

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#38]
What about introducing a shortcut for the selection of the zoom button ('z') and for zoom out ('f').
Also for peak-picking ...
as in other commercial NMR software!?

**Comment by lpatiny** [comment]
Funny I spoke with @hamed-musallam already about it and he was looking to implement this feature.

**Comment by hamed-musallam** [comment]
i implemented the this feature, you can check if you press z,f,p (zoom,full zoom out,peak picking)
