### ISSUE TITLE
Inverted phase after baseline correction

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#384]
If baseline correction (polynomial 5th order) is performed and apply is pressed, the phase of spectrum appears 180 degrees inverted. However, with a tiny move on the mousewheel, everything appear o.k. again.
![baseline-phase-during](https://user-images.githubusercontent.com/47237343/79778820-a7371180-8339-11ea-9bf0-b4310d405d1a.PNG)
![baseline-phase-after](https://user-images.githubusercontent.com/47237343/79778840-aaca9880-8339-11ea-9b88-e6e7b463594c.PNG)

**Comment by nes-cgn** [comment]
If PLS is used, the mousewheel 'trick' does not work, neither.

**Comment by hamed-musallam** [comment]
@nes-cgn 
I tested it with our example with the same degree value and it's work without any problem, can you upload spectrum that you used to test this feature so we can simulate the same condition 

![image](https://user-images.githubusercontent.com/35760236/79848605-97631000-83c1-11ea-97d4-b776253465d1.png)

after apply base line correction 

![image](https://user-images.githubusercontent.com/35760236/79848729-c2e5fa80-83c1-11ea-8206-02d0085d65af.png)

**Comment by nes-cgn** [comment]
Here is the file. However, in this moment, there is absolutely no problem - so it was a non-reproducible bug, I guess due to temporary changes on the code? Last night, it definitively existed

[1h.zip](https://github.com/cheminfo/nmr-displayer/files/4509254/1h.zip)

**Comment by hamed-musallam** [comment]
@nes-cgn 
i used the spectrum that you sent, and the problem not appear, are you sure this the correct file because the spectrum not have problem in baseline to apply the baseline correction on it.

**Comment by nes-cgn** [comment]
Hello Hamed,
yes - I told you that the problem does not persist now. When I tried  
yesterday, it was there. May I close the issue?

Quoting hamed-musallam <notifications@github.com>:

> @nes-cgn
> i used the spectrum that you sent, and the problem not appear, are  
> you sure this the correct file because the spectrum not have problem  
> in baseline to apply the baseline correction on it.
