### ISSUE TITLE
Mousewheel action for scaling

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#385]
Mouse wheel action for scaling either too slow or to fast (change of sensitivity or coarse/fine would be useful). Maybe instead also something like the *2 or *8 Funktion in TopSpin

**Comment by hamed-musallam** [comment]
@nes-cgn 
can you check if the new changes that i made it's what you need or not, if yes then please let me know so i can close this ticket
![image](https://user-images.githubusercontent.com/35760236/80033157-88c54780-84ec-11ea-95af-cdc5452a8baf.png)

**Comment by nes-cgn** [comment]
Hello Hamed,

I checked the mousewheel sensitivity and it looks good: High stands  
for increase scale, low for decrease, I guess? It is not  
clear/intuitive, what ranges of values are available. That's my only  
note, besides that it works great


Zitat von hamed-musallam <notifications@github.com>:

> @nes-cgn
> can you check if the new changes that i made it's what you need or  
> not, if yes then please let me know so i can close this ticket
> ![image](https://user-images.githubusercontent.com/35760236/80033157-88c54780-84ec-11ea-95af-cdc5452a8baf.png)

**Comment by hamed-musallam** [comment]
@nes-cgn 

At lest the smallest values for the two variables (high,low) is 1 and you can then put any number more than one. but i think it's better to have range of values and we can decide what the maximum value from your users experiments.

What do think the acceptable maximum value  for high and low from your using experiments.
