### ISSUE TITLE
Integration features

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#386]
When moving cursor to integral, the value should be shown instead only coordinates (or a pop up value appears or sth like that). Also, each integral should be possible to be defined to a value (e.g. setting a specific signal’s integral to 1), the initial default value for a signal should be rather 1 than a big number.

**Comment by hamed-musallam** [comment]
@lpatiny @nes-cgn 

I display the integral value when the mouse come over it under the x axis
![image](https://user-images.githubusercontent.com/35760236/80190722-071d0900-8615-11ea-8a14-d1050660fb04.png)

**Comment by nes-cgn** [comment]
looks good to me! that is definitively a useful improvement

Zitat von hamed-musallam <notifications@github.com>:

> @lpatiny @nes-cgn
>
> I display the integral value when the mouse come over it under the x axis
> ![image](https://user-images.githubusercontent.com/35760236/80190722-071d0900-8615-11ea-8a14-d1050660fb04.png)
