### ISSUE TITLE
file name for visualization of multiple experiments 

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#388]
If multiple spectra are displayed – would it be possible/make sense to also show the name of the individual files to better distinguish them? E.g. in the spectra or information section of accordion menu

**Comment by hamed-musallam** [comment]
@lpatiny 
Where do you think it's better to show the file name?

**Comment by hamed-musallam** [comment]
@nes-cgn 
After I checked the code we already use the File name as a label but because the examples that we used its build manually, we  named the files.

you can check that by drag and drop any jcamp file on the Displayer and you will see that we used the file name

**Comment by nes-cgn** [comment]
Hello Hamed,

I am not convinced. Check the file that I attach: It is a zipped  
Bruker file from our lates spectrometer, and besides the fact that I  
cannot properly import it, it also does not show the proper file name.  
I add another one from the 500 MHz (also latest Bruker Software) and  
it does not show the name, neither),

Nils


Zitat von hamed-musallam <notifications@github.com>:

> @nes-cgn
> After I checked the code we already use the File name as a label but  
> because the examples that we used its build manually, we  named the  
> files.
>
> you can check that by drag and drop any jcamp file on the Displayer  
> and you will see that we used the file name
