### ISSUE TITLE
deleting selectively spectra in multiple spectra visualization session

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#389]
If there is more than one 1D spectrum in the spectrum tab, how can I selectively delete only one of them? The trash can is to delete all spectra, but individual deletion seems impossible?

**Comment by hamed-musallam** [comment]
@nes-cgn 
You can do it be make one of the spectrums active then press delete button, if you not make any of the spectrum activ the Display shows confirm dialog to delete before delete all spectrums.
