### ISSUE TITLE
Integration preferences - blanking spectrum?

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#390]
Integration of a 1D proton and going through preferences of these integrals in right panel: When I clicked on “save preferences” the whole page reloads and I had again blank window (no spectrum or anything I did before), not reproducible – 1/3 times

**Comment by hamed-musallam** [comment]
@nes-cgn 
i try to re-simulate again what happens with you by save preferences for 20 times but the bugs not appear.
