### ISSUE TITLE
Digital filter older Bruker data (XwinNMR)

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#391]
As examples, the following files cannot be phased or only when applying a huge phase correction when imported as jcamp-fid. Also, original, zipped Bruker files cannot be imported.
[aspirin-jcamp.zip](https://github.com/cheminfo/nmr-displayer/files/4508336/aspirin-jcamp.zip)
[1H-aspirin.zip](https://github.com/cheminfo/nmr-displayer/files/4508338/1H-aspirin.zip)
[1H-naphtoic.zip](https://github.com/cheminfo/nmr-displayer/files/4508346/1H-naphtoic.zip)
[naphtoic-jcamp.zip](https://github.com/cheminfo/nmr-displayer/files/4508348/naphtoic-jcamp.zip)

The information on the problem below is from Kirk Marat. It seems that the phasing problem only affects the older Bruker data (but there are huge amounts available of them, so it should work for them, too):

had a look at those data that you sent me. They all seem to have been recorded in 2005 or 2006 with XwinNMR 3.5 (Although they were converted to JCAMP more recently). The early generation digital filters used in Bruker spectrometers of that vintage specified the filter parameters with two
parameters:DSPFVS and DECIM from which you could get the required phase correction (group delay times 360) from a big look-up table. This created a problem in that if they ever changed their filters, then any processing software would have to have that table updated. To get around this, starting with the digital receiver unit (DRU) (Avance II ???), they added the group delay parameter (GRPDLY) as an acquisition parameter. So as long as the acquisition software calculated the correct group delay, updating the filters was easy. From the group delay parameter you then calculate the required first order phase shift with 360 x GRPDLY.

You will need to have something like:

// Early Bruker DSP.
// Now find the appropriate first-order phase constant. No nice neat formula,
// just a big UGLY empirical table based on the DSPFVS and DECIM parameters.

int decim = (int) Math.round(q.DECIM);
if(q.DSPFVS == 10 && q.aq_mode != SW_main.det_modes.CUSTOM_DSP)
{
switch(decim)
{
case 2: phase = 16110.0; break;
case 3: phase = 12060.0; break;
case 4: phase = 23985.0; break;
case 6: phase = 21270.0; break;
etc...... repeat for DSPFVS == 11 and 12

Then for newer systems:

// Later Bruker DSP
// For newer (Avance II and up) data, there actually is a nice neat formula based on the filter
// group delay value!
else if((q.DSPFVS >=20 && q.DSPFVS <= 23)
|| q.aq_mode == SW_main.det_modes.CUSTOM_DSP)
{ // new for Avance DRU data
phase = q.GRPDLY * 360.0; // as per Mike Englehardt (Bruker)
}
else if (q.DSPFVS == -1) // data has been converted to analog
{
return; // no DSP correction required
}

You can look in the SpinWorks source (src -> spinworks -> Fft.java) and find the dsp_phase() method to see the complete table. I have attached an article from Concepts in Magnetic Resonance on digital filters and why there is a group delay. When you get to the point of working on JEOL data, you will have to do the same thing!  Varian/Agilent apply the group delay correction for you before saving the FID, so you don't have to worry about if for those data.

[The article mentioned was by Detlef Moskau from Bruker/Günther
[cmr.10031.pdf](https://github.com/cheminfo/nmr-displayer/files/4508432/cmr.10031.pdf)
]

**Comment by jwist** [comment]
Thanks for sharing.  This is mostly solved.

![image](https://user-images.githubusercontent.com/5422279/80416437-bcf88980-8899-11ea-9e14-6e4707da93c7.png)

![image](https://user-images.githubusercontent.com/5422279/80417070-ca624380-889a-11ea-925c-50d35b376b98.png)
