### ISSUE TITLE
Story books

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#40]
We would need the following stories in storybook:
* [x] 1H NMR spectrum
* [x] 13C NMR spectrum
* [ ] 1H NMR spectrum FID
* [ ] 13C NMR spectrum FID
* [ ] 13C coupled and 13C decoupled superimposition
* [ ] 20 NMR spectra of metabo
* [x] 20 NMR fid of metabo
* [x] COSY with corresponding 1D spectrum
* [x] COSY + TOCSY + ROESY with corresponding 1D spectrum
* [x] HSQC + HMBC with corresponding 1D spectra

**Comment by hamed-musallam** [comment]
@lpatiny  
can you provide data smaples, jcamp files for each one.

**Comment by lpatiny** [comment]
@hamed-musallam Could you create a story book from jcamps ?

**Comment by hamed-musallam** [comment]
no i can't but i mean how i can determine if it's 1H or 3H when i drag and drop jcamp file, but i need array samples x and y to create the story book that you are request.

**Comment by jwist** [comment]
in the jcamp you can look for a line that says: ##$NUC1= <1H>

it means that the nucleus in the first dimension is 1H. If you look at the next line NUC2 it will help you to find out what nucleus is in the second dimension (if there is any)

By looking at NUC1, NUC2 and ev NUC3 you can find out what kind of experiment you have.
