### ISSUE TITLE
phase correction issue

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmr-displayer#404]
It looks like the values for the phase correction are not stored or retrieved correctly. When using the tool several time the behavior is unexpected. See picture.
![phasing](https://user-images.githubusercontent.com/5422279/80538370-41670d00-896b-11ea-9c2e-574c99215ba8.gif)

**Comment by hamed-musallam** [comment]
@jwist 
are you need to see the last values for ph0 and ph1 in the last phase correction?

**Comment by jwist** [comment]
It may be a good idea to see the last values, but most importantly when you
select the phase correction tool, the spectra should remain the same.
Sometime it happens that the phase is modified only by selecting the tool,
and this cannot be.

Director de la Oficina de Transferencia
de Resultados de Investigación (TTO)
Associate Professor of the Chemistry Department
Universidad del Valle, Cali, Colombia
website: http://www.cheminfo.org


*AVISO LEGAL:* Este mensaje y/o sus anexos son confidenciales y para uso
exclusivo de su destinatario intencional. Si usted no es el destinatario,
le informamos que no podrá usar, retener, imprimir, copiar, distribuir o
hacer público su contenido. Cualquier retención, revisión no autorizada,
distribución, divulgación, reenvío, copia, impresión, reproducción o uso
indebido de este mensaje y/o anexos, está estrictamente prohibida y
sancionada de acuerdo con la Ley 1273 de enero del 2009. Si ha recibido
este correo por error, por favor elimínelo e infórmenos al correo
info@correounivalle.edu.co <xxxxxx@correounivalle.edu.co> Si usted es el
destinatario, le solicitamos mantener reserva sobre el contenido, los datos
o información de contacto del remitente y en general sobre la información
de este documento y/o archivos adjuntos, a no ser que exista una
autorización explícita.

**Comment by lpatiny** [comment]
We need to see the last values but the process has always to be done from the original spectrum before phase correction. If it is done from the current spectrum (that has already a phase correction) we first need to cancel this phase correction (how to do this without reprocessing everything ?)

**Comment by hamed-musallam** [comment]
but every time you change the ph0 and ph1 we processing the last state of the data, so i don't know what is your goal from that, unless if we have to save data with each filter be applied

**Comment by lpatiny** [comment]
What does this mean ? That you process the difference of ph0 and ph1 from the previous values ? Or the last state from when you started to make the phase correction ?

Because if it is the last state when you start the phase correction there is a problem if you do it twice.

**Comment by hamed-musallam** [comment]
@lpatiny 
we get difference between previous and current value of ph0 and ph1 to apply the phase correction.

**Comment by hamed-musallam** [comment]
@lpatiny 
 i checked the last changes made by Alejandro, he use different way through it he look for best value for ph0 form the last state of the data after apply the phase correction and repete this every time you change the ph0 or ph1.

so to solve this we have to save the state of data after the last filter before the phase correction and then apply the phase correction using the new ph0 and ph1 values.

**Comment by jobo322** [comment]
I found that some times, the value of ph0 is stored as a string (looking in filter table), after that the behavior start to be wrong.

**Comment by hamed-musallam** [comment]
@jobo322 
Can you show me the case of ph0 when its type is string because i try re-simulate your case and it's always i get number see the image below
![image](https://user-images.githubusercontent.com/35760236/81051438-f779ac00-8ec1-11ea-9268-6b2f4d8b2833.png)

**Comment by jobo322** [comment]
it is difficult to replicate the error. I have not obtained it again. I mean the merging of values for ph0 and ph1 between a couple of manual search-and-apply seems to be fine.
