### ISSUE TITLE
Default number of decimals on peak label

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#41]
The number of decimals displayed in a peak label will depend on the nucleus.

I added a function that allows to retrieve it based on the nucleus.

https://github.com/cheminfo/nmr-displayer/blob/b962d785b30987997360d16e20601f69a78603a0/src/data/default.js

Please adapt the code to use those preferences.

**Comment by hamed-musallam** [comment]
@lpatiny 
how i can determine from the data that i get it  from jcamp file if spectrum 1h or 3h..

**Comment by lpatiny** [comment]
In Datum1D there will be meta.nucleus that will either contain '1h' or '13c' (later some other nucleus.
