### ISSUE TITLE
Coffee example not working anymore

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#414]
![image](https://user-images.githubusercontent.com/1484241/80686634-4c37b400-8ac9-11ea-8ad4-9701410afbdb.png)

@jwist Is this related to your changes ?

**Comment by hamed-musallam** [comment]
@lpatiny 
i think it's better to assign it to @jwist because it's related to last changes in digital filter.

**Comment by jwist** [comment]
It is most probably related to my modifications. I will check.

**Comment by lpatiny** [comment]
I added a condition to only check for digitalfilter if it if a fid.
