### ISSUE TITLE
Improve integrals preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#423]
* Use react-mf for 1H (nucleus)
* change name 'nb' by 'Relative'
![image](https://user-images.githubusercontent.com/1484241/81046545-ec6e4e00-8eb8-11ea-9498-8f5482574ba0.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
do you want to change the title of the column 
![image](https://user-images.githubusercontent.com/35760236/81052620-12e5b680-8ec4-11ea-9f82-3a8c96248ec5.png)
