### ISSUE TITLE
Add preferences to ranges

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#425]
Prepare the preferences for the Ranges panel similar to integral

All those preferences should be global and I think by default stored in localStorage (this could be manage from outside the component in the future).

**Comment by hamed-musallam** [comment]
@lpatiny 
we save all the preferences option in the JSON file when export it so it's global per sample and if you import the JSON again you will have the same preference that you have when you save the file

**Comment by lpatiny** [comment]
There should be a way to save as default preferences in localStorage. Most of the time we will not reload the data from a json but we will have either zip / jcamp
