### ISSUE TITLE
Autophase correction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#429]
Add an algorithm for auto phase correction

**Comment by jobo322** [comment]
In the PR [#463](https://github.com/cheminfo/nmr-displayer/pull/463) I did add the filter that returns phased to update datum1D and ph0 and ph1 to update the filter parameters

**Comment by lpatiny** [comment]
Noise detection could be done using @djeanner algorithm as described in https://github.com/cheminfo/nmr-displayer/issues/39

This algorithm was never implement but could be implement in spectra-processing

**Comment by lpatiny** [comment]
@jobo322 I updated to the last version but there is still some issues trying to autophase the 13C after FT. Nothing happens
