### ISSUE TITLE
feature: add the possibility to display a tree that represents the multiplet

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmr-displayer#439]
![image](https://user-images.githubusercontent.com/5422279/81077327-736bf800-8eb2-11ea-8c86-87bc7f3ca4f9.png)

See: http://www.cheminfo.org/Spectra/NMR/Tools/Multiplet_simulator/index.html

**Comment by djeanner** [comment]
Very nice indeed!
If the "copy url" could allow to return to the same multiplet (so the one could show someoneelse a multiplet) it would be even better... You don't have to save the cession, but have the J,m as arguments when  the page is called!
Anyways, nice....

**Comment by djeanner** [comment]
A fabulous feature would be to be able to drop a spectrum on top of the simulation (so that we could do manual adjustments.... have little buttons to increase, decrease J's.... or with the mouse....
