### ISSUE TITLE
advanced feature: add zone that can trigger action on multiple spectra

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmr-displayer#447]
Add zones, annotations as ranges, but that will apply an action on all the displayed spectra. This can be used to integrate the same area in different spectra and display a kinetics.

**Comment by lpatiny** [comment]
Add a new tool that is present only in case of multiple 1D spectra

- There is a tool that allows to define a range (same annotation that the smart peak picking)
- There is a panel for multiple spectra analysis
  - each line is a spectrum
  - 2 columns per range: the integration and the δ of the highest peak (configurable in preferences)

**Comment by hamed-musallam** [comment]
@lpatiny 
Is it a good way if I store the detected ranges inside the ranges array for each spectra so we can export it and also we can see ranges inside the ranges panel when we select specific spectra, or you do not want to store it at all.
are this tool going to work per nucleus or for all 1d spectra?
