### ISSUE TITLE
2D: display projections (vertical and horizontal)

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmr-displayer#450]
display vertical and horizontal projection (row and column) at the selected point.

**Comment by hamed-musallam** [comment]
@jwist 
i think you have to assign it also to @jobo322 once he is finished the work from this side then i will do the reset stuff from my side.

**Comment by jwist** [comment]
Sorry, because of the meeting I had no time to elaborate. The idea is pretty simple. When you hover the spectra you can select a data point, i.e., you get the index of the column and the row of that point. The idea consist in displaying the row and the column (both are 1D traces) on top of the 2D data. This option can be a tool that you select from the tool button. When this tool is toggled then the 2 traces will be visible on top of the 2D. Hope this helps.

**Comment by lpatiny** [comment]
Adding a new tool makes sense. This can justify that sudently we hide the spectra that were selected as 1D and display so other spectra that are being generated.

**Comment by lpatiny** [comment]
@hamed-musallam 
Could you call this method:
https://github.com/cheminfo/nmr-displayer/blob/6def60624574bac843a2ebeaed13dfa1c4b061e0/src/data/Analysis.js#L155-L164
After I can create the 1D spectra from the data.

**Comment by hamed-musallam** [comment]
@lpatiny 
yes  i can call it. did you finished?

**Comment by lpatiny** [comment]
In order to add my code I need that you call this method so that I can debug on my side.

**Comment by hamed-musallam** [comment]
@lpatiny 
it's done, you can now call createProjection function to debug your work, i added addition parameter "position={x,y}" . to your function, you need to look for the closest values in the series for x and y

**Comment by hamed-musallam** [comment]
@lpatiny 
Can you complete createProjection function to test my work?

**Comment by lpatiny** [comment]
There was an inversion to do in my code but it looks ok now. We will open more tickets if there are some bugs.
