### ISSUE TITLE
Drag drop zip of bruker files yields to the same color spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#456]
Color should be different. We should keep the same color only for the couple FT / FID

![image](https://user-images.githubusercontent.com/1484241/81275248-b0222580-9051-11ea-8af2-4abd2fd3b58e.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
can you send to me some Bruker files as example?

**Comment by lpatiny** [comment]
I did by telegram. It was quite big
