### ISSUE TITLE
Drag drop separately 2D jcamp crash the application !

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#457]
[Archive.zip](https://github.com/cheminfo/nmr-displayer/files/4591927/Archive.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 
it's not produce any error but it's not load the data

**Comment by lpatiny** [comment]
If I drag hmbc and then drag hsqc I get

![image](https://user-images.githubusercontent.com/1484241/81277115-3c354c80-9054-11ea-9d2b-a2ab7e7269a1.png)
