### ISSUE TITLE
Add in text 'p' for phase correction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#468]
In the tooltip the shortcut is missing

![image](https://user-images.githubusercontent.com/1484241/81370805-59225c00-90f6-11ea-9d48-8b034dfa741d.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
we can't use this shortcut because we already use it for peak picking

**Comment by lpatiny** [comment]
Indeed. Let's put 'a' for now. This could be changed.
