### ISSUE TITLE
Fix phase correction control

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#471]
If I move slowly on the phase correction the value jump randomly positively and negatively while I continuously move in the same direction

![2020-05-08 06-46-35 2020-05-08 06_47_29](https://user-images.githubusercontent.com/1484241/81371321-d6020580-90f7-11ea-9d77-43de9dee0c61.gif)

**Comment by lpatiny** [comment]
Only the direction of the movement and the speed of the movement should could. I don't understand why it goes from positive to negative while I'm continuously move in the same direction. The position where I start the click is not important

**Comment by hamed-musallam** [comment]
@lpatiny 
i tried the something that you did but on windows OS i did not see this side effect at all
