### ISSUE TITLE
Add a drop down menu in phase correction like in baseline correction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#472]
The beginning of the line should contain a drop down menu:
- Manual:will display the current information
- Automatic: will apply the automatic phase correction (immediately) so that you can go back on manual for fine tuning. This is the new algorithm of Alejandro
- Absolute: will apply absolute (a new property in the filter) that will display the absolute value. This filter transforms a x,re,im object to a x,y object. Again you should preview directly the result.

Need to take care that this last filter (absolute) is not reversible and will not change PH0, PH1 but add the new property 'absolute': true / false. Need to take care what happens when we change the drop down menu.

We expect in the future to have other algorithm for automatic phase correction.

**Comment by hamed-musallam** [comment]
@lpatiny 
for Absolute option its only property i pass it to manual phase correction filter with out pass ph0 and ph1? or we have to save ph0 and ph1 temporary after the manual and  automatic phase correction. 
are you need only to apply automatic phase correction filter once you select this option from the drop down list and others when you press apply?

the Automatic phase correction will done on temp data and not on the real one until you press apply.

what do you mean " (absolute) is not reversible " that mean that you can't enable and disable filter if it's absolute .
