### ISSUE TITLE
Many open panels at the same time

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#483]
We will have to be able to have many panels open at the same time. For example the molecule and the ranges will be a must.

The height of the panel title could be smaller

![image](https://user-images.githubusercontent.com/1484241/81506019-e7affc80-92f3-11ea-8b0b-7701e9c4a43d.png)

When clicking once on the title it opens but does not close the other panels. They need to share the space.

If you click twice it will take the full space (and close all the other panels).

Like currently if you click once of the title it toggles (open / close)

We need a way to resize the different panels by move the space between them (here is an example from inkscape)

![image](https://user-images.githubusercontent.com/1484241/81506126-791f6e80-92f4-11ea-8f0c-aba3714500a8.png)

**Comment by lpatiny** [comment]
If more than one panel is open at the same time they share the space by default (50:50 or 33:33:33) but this can be changed manualy.

**Comment by lpatiny** [comment]
The current feature is nice. How difficult it is to make them resizable ?

**Comment by hamed-musallam** [comment]
@lpatiny 
i layout the panels with Flexbox to distribute the displayer height between panels, i think we can save global preference to save that this panel will take flex:2 or 3 but i don't imagine where to put this preference so the user can change it

**Comment by lpatiny** [comment]
I was thinking resizing like: https://reactjsexample.com/resizable-flex-layout-container-components-for-advanced-react-web-applications/

Interactively like you do between the panels and the spectrum

**Comment by lpatiny** [comment]
This was implemented
