### ISSUE TITLE
Default selection of spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#486]
When we drag and drop a jcamp containing FT and FID we display the FT by default. This is perfect. We should also however select the first spectrum after FT by default. Currently nothing is selected.

[1H_Cytisin.dx.zip](https://github.com/cheminfo/nmr-displayer/files/4627368/1H_Cytisin.dx.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 
because we agreed in previous ticket that if we in 1d mode and have more than on spectrum not to select any one.
https://github.com/cheminfo/nmr-displayer/issues/407#issue-609663177

**Comment by lpatiny** [comment]
You are right indeed. But if there is only once spectrum after FT it should still be selected ;)

**Comment by lpatiny** [comment]
It should be the one after FT and not before ft. Currently you display the FID (before FT)
![image](https://user-images.githubusercontent.com/1484241/81966195-720c9f00-9619-11ea-9336-e7885028d26d.png)
