### ISSUE TITLE
Hide buttons if there is no selected spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#487]
Currently even if there is no selected spectrum we can select the integral, range, etc. While actually they can not be used.

This is quite confusing. If the button can not be used we should hide the button.

**Comment by hamed-musallam** [comment]
Which buttons you need me to hide it can you put some images?

**Comment by lpatiny** [comment]
Drag and drop of the spectrum this morning was not loading any default spectra but still the integral button was available. This is not the case anymore anymore because the spectrum is selected. I close this ticket for now.
