### ISSUE TITLE
Processed 13C spectrum does not have the correct phase

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#489]
https://cheminfo.github.io/nmr-displayer/#/SamplesDashboard/fbo21emj416/datacytisinedatacytisineprocessed13Cjson

Maybe it is just a question of reprocessing, save and update the example ?

**Comment by hamed-musallam** [comment]
@lpatiny 
you have first to reprocess the filter on 13c FID, because we have problem in it after the modification on digital filter.

**Comment by hamed-musallam** [comment]
@lpatiny 
i found the problem in digital filter after we update the digital filter the input parameters also changed so i changed it from{"dspfvs": "20","decim": "554.666666666667","grpdly":"67.9918823242188"} to {"digitalFilterValue":67.9918823242188}
