### ISSUE TITLE
Migrate 2D peak picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#492]
Migrate code from spectra to nmr-processing

**Comment by jobo322** [comment]
@lpatiny @hamed-musallam in 2D the autoPeakPicking has access to datum1D (see [peakActions](https://github.com/cheminfo/nmr-displayer/blob/master/src/component/reducer/actions/PeaksActions.js)) could we add a new tool or modify it?

**Comment by hamed-musallam** [comment]
it's done
