### ISSUE TITLE
New panel for Ranges 2D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#498]
Create a new panel for Ranges 2D that display that list all the 2D zones being drawn.

There should also be highlight between the drawn zone and the lines in the table.

**Comment by hamed-musallam** [comment]
@lpatiny 
is it for 2d integral tool that i already done it that draw rectangles over the 2d spectrum or it's a new tool for ranges

**Comment by lpatiny** [comment]
For the tool that is already done. We will not for 2D make a tool for integration and a tool for ranges. Only one is enough.
