### ISSUE TITLE
Delet all integrals

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#539]
Hi,
at the moment it isn´t possible to "delete all integral" if you work with the full screen. You have to leave the full screen, than you can see the red box with "yes" and "no".
Kind regard, 
Eva

**Comment by hamed-musallam** [comment]
@evaziegler 
right now you are right this actual what happen, but let me check if i can solve this problem or not.
I will let you know once i check it.

**Comment by hamed-musallam** [comment]
@evaziegler 
i fixed the problem, so you can now see the delete modal and other types of modal even if you in the full screen mode
