### ISSUE TITLE
Create a build of the help

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#563]
There should be a npm script that builds the docs as HTML and publish it on the gh-pages of the project. The github action should be adapted to build the documentation as well.

Something like:

/docs/master/xxx

Or

/docs/master/vx.y.z/...

The documentation base url could be defined as the react  property and by default https://cheminfo.github.io/nmr-displayer/

**Comment by hamed-musallam** [comment]
it's done
