### ISSUE TITLE
Create a new view for tests / exams

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#569]
Create a new view that does not display if the answer is correct but rather displays the SMILES code of the answer

So a view like Èxercise.jsx` called `Exam.jsx` and in the bottom right your display the currently drawn smiles. this can be done by using `molecule.toSmiles()`

We should be able to select and copy the smiles so that it can be pasted in another system. 

There should also be an example on the home page showing the result of this `view`

**Comment by hamed-musallam** [comment]
@lpatiny 
Do you want to store the Exam is taken flag in Browser indexdb? because you know if we store in the browser then if the user open new browser or even if he clear the browser data  he will see all the exams.

**Comment by hamed-musallam** [comment]
@lpatiny 
can you explain this "There should also be an example on the home page showing the result of this view"

**Comment by lpatiny** [comment]
Add al ink like:
![image](https://user-images.githubusercontent.com/1484241/93194186-19c0e780-f748-11ea-9fd5-0d9cd4e0a8f5.png)

We may store locally but they idea is that they copy / paste their answer in another program (moodle)
