### ISSUE TITLE
Number of digits

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#592]
Should depend of nucleus

Should be configurable in the general preferences

Saved in localStorage with default values that are the currently used one.

**Comment by hamed-musallam** [comment]
@lpatiny 
What is the label for these new fields in general setting and what the default values, second thing do we have "format field" for each nucleus and what is we going to do if we have different nucleus according to spectrums samples that we have in each example

**Comment by lpatiny** [comment]
We need a table with 3 columns

1. nucleus (formatted with new isotope component)
2. format for "δ (ppm)"
3. format for coupling "Coupling (Hz)"

**Comment by michaelwenk** [comment]
@hamed-musallam We also need a possibility (column/field) to set a chemical shift tolerance value when we do the shift matching of same nucleus type between spectra. 
For example, we want to figure out which signals (delta values) in a 1D 13C spectrum match against signals in 2D HSQC spectrum (on y axis in this case for 13C). 
To have a tolerance window we need such general settings per nucleus.

**Comment by hamed-musallam** [comment]
@michaelwenk 
it's done, but you have to open new ticket for https://github.com/cheminfo/nmr-displayer/issues/592#issuecomment-707016258
