### ISSUE TITLE
NMR 2D example

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#593]
We would need a new serrie of exercise for 2D NMR 

https://github.com/cheminfo/nmr-dataset1/tree/master/data

This means at the first level there should be a JSON file `2D.json` similar to https://github.com/cheminfo/nmr-dataset2/blob/master/docs/toc.json

In this JSON we will have 2 exercises:
- First exercise from: https://github.com/cheminfo/nmr-dataset1/blob/master/data/620-71-3/
  - 13c.dx
  - 1h.dx
  - coxy.dx
  - hmbc.dx
  - hsqc.dx
  - 1dnoe.dx
  - structure.mol (the answer)
- Second exercise: https://github.com/cheminfo/nmr-dataset1/tree/master/data/2759-55-9
  - 13c.fid.dx
  - 1h.fid.dx
  - coxy.dx
  - hmbc.dx
  - hsqc.dx
  - structure.mol (the answer)

Add an exexmple in the rEADME of nmr-displayer to this test

**Comment by hamed-musallam** [comment]
it's done
