### ISSUE TITLE
Let story book work

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#6]

**Comment by lpatiny** [comment]
The storybook should be published in a new branch: `gh-pages`
In the settings of the project you should then define this branch as the source:
![image](https://user-images.githubusercontent.com/1484241/60241190-f7c51600-98b2-11e9-9b6c-39889e4c512f.png)

**Comment by hamed-musallam** [comment]
I build it you can check it directly at github.
