### ISSUE TITLE
Integral relative should be editable

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#603]
![image](https://user-images.githubusercontent.com/1484241/94647924-ccb94580-02f1-11eb-88b9-4ffcaac83853.png)

If we double click on the value it should be in-place editable and enter to validate.

When validating the value you need to calculate the ratio between the previous value and the current value and then apply the same ratio to the sum. Changing the sum should trigger the recalculation of all the relative integrals and it should be the correct (expected) result.

**Comment by hamed-musallam** [comment]
@lpatiny 
what is going to happen if we do not have sum yet and we edit the integral value?
if we  have sum value and we edit the integral are we going to take the ratio between the old and the new value and change the sum value or we just redistribute the integral values according to the same sum before edit ?

**Comment by hamed-musallam** [comment]
it's done
