### ISSUE TITLE
Peak picking for positive and negative (e.g. DEPT or multiplicity-edited HSQC)

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmr-displayer#612]
At the moment, it seems to that there is no way to detect signals within DEPT spectra in positive AND negative direction. So negative direction is missing.   

@lpatiny @jobo322 Is there already something planned for implementing this?

**Comment by lpatiny** [comment]
@jobo322 How can peak picking work for positive and negative peaks (using current algorithm) ? Should we invert the spectrum and redo peak picking to get the negative peaks ?

**Comment by michaelwenk** [comment]
@lpatiny @jobo322 Something like that we also need for 2D experiments like the multiplicity-edited HSQC. Both algorithms (1D and 2D) should then give some kind of sign for each signal to distinguish too.

**Comment by jobo322** [comment]
@lpatiny @michaelwenk for 1D peak detection we could apply the algorithm twice or refactor the code to also check a minimum at the first derivative and maximum at the second derivative.

For 2D peak detection, I am not pretty sure how to modify it yet, I'm checking the possibilities.

**Comment by jobo322** [comment]
@michaelwenk could you check the peak detection at 2D with this [file](https://dl.dropboxusercontent.com/s/jvn5huvwflt0sgc/exam2d_HC.dx?dl=0)

**Comment by lpatiny** [comment]
I would do the following:

1. Calculate the absolute value https://github.com/mljs/spectra-processing/blob/master/src/x/xAbsolute.js
2. Make the usual GSD
3. For each peak invert the sign if at the pixel found the original value is negative

**Comment by jobo322** [comment]
@michaelwenk could you check with a 2D spectrum if the negative signal is detected? For 1D it is done and tested. I think for 2D it should be working but I have been not tested it well

**Comment by michaelwenk** [comment]
@jobo322 Around two or three weeks ago I implemented the detection of the number of attached protons via multiplicity edited HSQC. At that time I already could also see positive and negative peaks from 2D zones picking in this project and use it for the sign determination. 
So at least for my test cases it works.

**Comment by jobo322** [comment]
Ok I will add optimization of the parameters in 2D.
