### ISSUE TITLE
Contour plot calculation speed ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#618]
I have the impression that HMBC vertical scaling is again (still ?) very slow.

Clearly the contour plot calculation

![image](https://user-images.githubusercontent.com/1484241/95163214-ac80ff00-07a7-11eb-9ec0-37159cf76071.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
i reduced the timeout from 4000 MS to 2000 MS, locally the speed is become better but in gh-pages site not too much may be it's related to the resources that allocated for node js at GitHub, can you pull the changes and test

**Comment by lpatiny** [comment]
We filled a bug report on immer github: https://github.com/immerjs/immer/issues/681
