### ISSUE TITLE
Undo / Redo - Save / Load

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#62]
All the undo / redo must be at the end at the level of the application. We will have many Datum1D and many Datum2D.

### At the level of Datum1D
Undo / redo:
* to keep track of the filters and be able to undo / redo a filter
* to keep track of the addition / suppression of integrals.
* to keep track of the addition / suppression of peaks
* keep track of some display option changes (like color change for example)
* ...

Load / save:
A json that stores all the information about all the Spectrum1D, Spectrum2D, position of the spectra, color of the spectra, etc.

At the level of a Spectrum1D
* save a json that contains: 
  * filters
  * display options (also vertical scale)
  * integrals
  * peaks

At the beginning we should reapply all the filters (from the original spectrum) if the undo is related to a filter. This is anyway what we will save and we could optimise this later by checking by keeping some intermediate results

**Comment by nes-cgn** [comment]
Undo/redo currently does not work

**Comment by lpatiny** [comment]
Load save was implemented. Undo / redo duplicate of https://github.com/cheminfo/nmr-displayer/issues/768
