### ISSUE TITLE
2D exercises, field distribution and visible menu bars

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#623]
For the 2D exercises available at
https://cheminfo.github.io/nmr-displayer/#/?sampleURL=https%3A//cheminfo.github.io/nmr-dataset1/data/2d.json
the displayed 2D experiment should be with more space and the structure editor (below) can be reduced drastically in size. 
Currently, one can only appreciate the 2D if opening them in full screen mode. Some arrangement as used for the standard displayer (e.g. HSQC cytisine) would be favourable. Maybe it would help to put the molecular formula below the spectrum and have the editor on the right side. Instead of only integrals, for 2D interpretation purposes, the zone function would be also useful.

In exercise 1 (620-71-3, in list from nmr-dataset1 it is position #2) the HMQC is missing. This is because in the file "ex.json", in line 68, it says HSQC instead of HMQC.

In exercise 2 (2759-55-9, in list from nmr-dataset1 it is position #3) the experiments can almost never be loaded in my computer, the program crashes.

**Comment by nes-cgn** [comment]
Now, it looks much better. But it would still be more convenient to have the editor to the right (where there is now the molecular formula) and maybe like that also to have the option to expand the spectral window also downwards. The full screen mode does not substitute such an option

**Comment by hamed-musallam** [comment]
@nes-cgn 
you must be aware that the are A (NMR-displayer Block) as you see in the image below one block so you can not expand the panel are at the right side without expanding the whole A area and this applies also to the tools are and draw area.

What is the idea if you move area B (molecule structure editor) under the  C area (Molecule Formula)?
 

![image](https://user-images.githubusercontent.com/35760236/97676134-7413ce80-1a90-11eb-9e10-b2ad69d04a82.png)

**Comment by nes-cgn** [comment]
Well, the main aim for such an excercise is that you can clearly recognize the spectra. So, as it currently appears, the 2D spectra will either show up as very small and stretched rectangles on top of a (kind of oversized) area B and C. Or you have to move to fullscreen mode, where the editor and the molecular formula are not visible.
I thought rather in something like the thing that you see in the screenshot here
![2D-exercise-301020](https://user-images.githubusercontent.com/47237343/97704583-f7461c00-1ab2-11eb-88f5-0ca47033b263.PNG)
Would it be possible to either include the structure editor in a bar menu of the accordeon column or make it pop-up somewhere? The results/information given in C is important, but the area is oversized, too. If it would be possible to make that smaller, one could maybe put the formula region to the left of a ribbon that covers one entire column, with the results section on the right hand side. Like that, it would not occupy so much space

**Comment by lpatiny** [comment]
@hamed-musallam Please give the possibility to hide / show all the bottom part (drawing tool and result). The student will open it when he found the structure.

![image](https://user-images.githubusercontent.com/1484241/98211326-2ab8f880-1f42-11eb-89d6-342f56e9c793.png)
