### ISSUE TITLE
Check how we calculate integratioin for 1D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#626]
Something similar should be done for 2D

**Comment by hamed-musallam** [comment]
it's done

**Comment by lpatiny** [comment]
Can you add a link to the commit ? Did you calculate integration for the 2D ?

**Comment by hamed-musallam** [comment]
@lpatiny 
only for 1d, 
https://github.com/cheminfo/nmr-displayer/commit/26ad6326e738439094ca97e04d0295260493ffbe
