### ISSUE TITLE
Allow component to switch to full screen

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#64]
Would be nice to easily switch to full screen. Maybe this component could do the jjob:

https://www.npmjs.com/package/react-full-screen

**Comment by hamed-musallam** [comment]
the component is broken when going back from the full screen when pressing ESC or click on close button

**Comment by lpatiny** [comment]
@hamed-musallam  Please try this one: https://www.npmjs.com/package/react-request-fullscreen

**Comment by lpatiny** [comment]
Try to fix the current react component. It goes to full screen but does not resize always the component. Works in firefox.
