### ISSUE TITLE
Selection in general settings to show/hide panels 

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmr-displayer#641]
@hamed-musallam It would be nice to have the possibility to select panels to show or hide.
The general settings could be a good place for this:

<img width="139" alt="Bildschirmfoto 2020-10-08 um 23 17 49" src="https://user-images.githubusercontent.com/30418272/95514834-ebd46900-09bc-11eb-8452-8f749b889676.png">

@lpatiny  I can not assign to or label or close an issue because I don't have write access to this project, I guess.

**Comment by hamed-musallam** [comment]
@lpatiny 
What do you think? do we need to have something like that in general setting or you different idea.

**Comment by lpatiny** [comment]
Yes it is a nice feature to have !
