### ISSUE TITLE
can not import bruker file 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#651]
these samples sent from Nils but unfortunately, we can not import it and I get an error from the import brushed function.

[Uploading 141-32-2.zip…]()

[Displayer_50-78-2.zip](https://github.com/cheminfo/nmr-displayer/files/5438373/Displayer_50-78-2.zip)
-2.zip…]()

![image](https://user-images.githubusercontent.com/35760236/97164537-918c2400-1782-11eb-863b-8cee3ee79b78.png)

**Comment by jobo322** [comment]
I will check it

**Comment by hamed-musallam** [comment]
fixed by @jobo322
update nmr-parser b9e26b936b44087f8a0dfd94ddd09a1d20edbc61
