### ISSUE TITLE
Crash when manual or automatic 2D zones picking

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmr-displayer#654]
@jobo322 @lpatiny 

<img width="839" alt="Bildschirmfoto 2020-10-28 um 11 57 41" src="https://user-images.githubusercontent.com/30418272/97427644-26bf2200-1915-11eb-8773-35e15fa1678b.png">

**Comment by hamed-musallam** [comment]
@jobo322 
I updated the nmr-processing package to the last release do i have to return back to the old one

**Comment by jobo322** [comment]
I did a PR, could you check if this solves your problem?
