### ISSUE TITLE
do not automatically zoom out when (de)selecting filters 

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#657]
When using the filter menu (i.e. deselecting and re-selecting filters to study their effect) it would be good if the - currently active - automatic zoom out would not be applied. E.g. if you want to study the effect on a complex multiplet, it would be good to stay throughout the changes on the filters in the same zoomed-in region

**Comment by hamed-musallam** [comment]
@nes-cgn 
do you mean de/select the filters from the filters panel?

![image](https://user-images.githubusercontent.com/35760236/97630934-8b22d400-1a30-11eb-821d-f1e1653767a3.png)

**Comment by nes-cgn** [comment]
What I mean is, that if I deselect those filters, the window with the spectrum switches back to the full spectrum view. Which is not desired, esp. if you would like to study the effect on multiplets

**Comment by lpatiny** [comment]
This should only be done if we keep the same scale. Because if we remove FT we should anyway zoom out.

**Comment by nes-cgn** [comment]
It is also an issue for 2D experiments. Let's say, you are looking at an HMQC and an HMBC spectrum at the same time. You zoom into one region to check something, and then you want to make disappear/re-appear one of the experiments (e.g. HMQC). After each click on the "eye", the full scale will be recovered which is not desired.

**Comment by nes-cgn** [comment]
![HMQC-HMBC-dual](https://user-images.githubusercontent.com/47237343/104698237-59f1a000-5711-11eb-9024-e30ea571aaf5.PNG)
![HMBC-hmqc-transparent](https://user-images.githubusercontent.com/47237343/104698260-6118ae00-5711-11eb-8a2e-e53c5d30719e.PNG)

Currently you can make spectra transparent, by clicking the active one twice, but you cannot make them disappear without resetting the scale.
