### ISSUE TITLE
Be able to delete a column

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#661]
Multiple spectra analysis should allow to delete a column

![image](https://user-images.githubusercontent.com/1484241/97704851-69b6fc00-1ab3-11eb-9ca2-d400404a18f8.png)

**Comment by hamed-musallam** [comment]
@lpatiny you can delete it if your mouse over the green rectangle and then click on the delete button.

**Comment by lpatiny** [comment]
This would be an alternative way. Will also be useful when we add calculation columns.
