### ISSUE TITLE
Why all integrals are 100 ??

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#662]
First time we create a range everything is 100

We should not display a relative integral but an absolute integral seems to me.

![image](https://user-images.githubusercontent.com/1484241/97705085-c5818500-1ab3-11eb-95bc-3dc78fbdb5c7.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

The relative value it is going to be 100 for the first time because the sum is 100 and then if you add more column the relative value is change according to weight of absolute

**Comment by hamed-musallam** [comment]
Is relative is going to be between ranges for the same spectrum or between the range for spectra.

**Comment by lpatiny** [comment]
The first spectrum should be 100 and define the ratio between the absolute integral and relative integral that should be applied to the other spectra.

If could (should) be a preference for a column to have it as a reference column and in this case this column would be 100.
