### ISSUE TITLE
Column preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#667]
Each column in the multiple spectra analysis could have the following preferences

- variable name
- value is the integral
- value is the maximum intensity
- value is the minimum intensity

This means that for each range we should calculate an object containing:
- integral, min and max

**Comment by hamed-musallam** [comment]
@lpatiny  
we can change the variable name as you suggested here so I think it's related to #666, instead of changing the column name in the table header we can do it from preferences I think it's better.

**Comment by lpatiny** [comment]
And this case you can complete: https://github.com/cheminfo/nmr-displayer/blob/master/.ncurc

Maybe you could also check the other module we fixed the version to know if it should still be the case.
