### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#669]
Please update all dependencies. The new major release of react-dom seems to crash nmr-displayer

**Comment by hamed-musallam** [comment]
@lpatiny 
I did not update react and react-dom, because there are breaking changes that happened to event delegation this why I delay it to another time.
 
https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

**Comment by lpatiny** [comment]
And this case you can complete: https://github.com/cheminfo/nmr-displayer/blob/master/.ncurc

Maybe you could also check the other module we fixed the version to know if it should still be the case.
