### ISSUE TITLE
Multiple spectra analysis is too slow

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#670]
Based on the Performance seems this code call analyseMultiplet and this should not be the case

![image](https://user-images.githubusercontent.com/1484241/97708141-97eb0a80-1ab8-11eb-82b6-2a79ae13ee1c.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
it's related to the function that we use from the ml-spectra-analysis and multiple-analysis package the speed depend on how much wide is, if you zoom in into specific are and select a precise area it will be fast.

![image](https://user-images.githubusercontent.com/35760236/97753299-cfc47300-1af5-11eb-9f0b-d05ffd46c085.png)

**Comment by lpatiny** [comment]
This full code should not be executed. It is used for the multiplet analysis but here we only calculate integral.
