### ISSUE TITLE
ranges picking with 1D and 2D experiments in data set

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#673]
The following situation produces a problem/crash of displayer: If I use the data set consisting of a 1H and COSY from dataset 91-64-5 in the light version and as jcamp files, I can import the spectra (also, there is no problem to add a 13C and HMQC/HMBC) and switch between them. However, once I define even a single range in the 1H experiment, as soon as I attempt to see the COSY, the displayer crashes.  The data are in the nmr-dataset1 file but I add them here:

[1-preproc-dx-full.zip](https://github.com/cheminfo/nmr-displayer/files/5479421/1-preproc-dx-full.zip)

It also happens if I directly go for the Bruker TopSpin files:

[Displayer_91-64-5_light.zip](https://github.com/cheminfo/nmr-displayer/files/5479432/Displayer_91-64-5_light.zip)

The same occurs with other of the nmr-dataset1 examples, too. As soon as ranges are selected in the 1D, the 2D visualisation produces a problem.

**Comment by hamed-musallam** [comment]
@nes-cgn 
i test it using your samples but unfortunately i can not reproduce the bug... may be you don not mention something lead to this bug??

**Comment by lpatiny** [comment]
Can this be reproduced with Cytisine testcase ?

![image](https://user-images.githubusercontent.com/1484241/97956145-353f8a80-1da8-11eb-9575-5e01370d6e06.png)

I can not reproduce the problem.

**Comment by nes-cgn** [comment]
Here is a little movie that shows the problem
[bug_673.zip](https://github.com/cheminfo/nmr-displayer/files/5479725/bug_673.zip)
It occurs also with aspirin 50-78-2 (jcamp files, light version), with 86-55-5, with 140-67-0, with 141-32-2 etc.
You can see it if you pull a 1H and a COSY, then define ranges in 1H and after that change to COSY.
