### ISSUE TITLE
Integrals in plot/export function

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#678]
There should be a way to define that integral values are also printed in the export graph. Currently, only the integral trail can be seen, but students would like to have a number (below the axis, e.g. ) that tells them the volumes

**Comment by nes-cgn** [comment]
Also, it would be cool if the integral trails could be moved up/down or so, because currently, if watching the spectrum with the CA mode, the integrals look kind of weird.

**Comment by lpatiny** [comment]
@nes-cgn please open different tickets and don't mix 2 problems. Otherwise it is not possible to solve one of the problem and close the ticket.
