### ISSUE TITLE
Allow to hide / show all the panels.

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#679]
Add a way to hide completely the panels like it is done for the examples

![image](https://user-images.githubusercontent.com/1484241/98211176-f2191f00-1f41-11eb-992d-1593c58da730.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
what do you mean the leftright panel??? do you mean hide the right panel totally if you hide all the panels from the general settings.

**Comment by lpatiny** [comment]
Have something like:

![image](https://user-images.githubusercontent.com/1484241/98673274-69421f00-2357-11eb-88b6-1bb8c59dbed3.png)

To hide all the panels (that are on the right) and keep only the spectra.

**Comment by hamed-musallam** [comment]
@lpatiny 
you can now do this by double click on the resizer area 
![image](https://user-images.githubusercontent.com/35760236/99061695-3b044f80-25a2-11eb-9c4a-356c50546312.png)
