### ISSUE TITLE
Dataset for T1 measurement

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#685]
Could we have a dataset (many 1D NMR spectra) that would allow to make the T1 measurement ?

**Comment by nes-cgn** [comment]
I will send you data. Just not before the weekend, since I got tons of teaching to do currently

**Comment by lpatiny** [comment]
@hamed could you check with @nes-cgn and add the T1 experiments in a similar way as the coffee ?

This will allow us to continue the multiple spectra analysis with a real useful case.

**Comment by hamed-musallam** [comment]
@lpatiny 
No problem once he prepares it I will include it inside the demo

**Comment by nes-cgn** [comment]
Here are the 1H jcamp files (pseudo 2D plus delay list with delay information, as well as individual 1D files extracted from 2D)

[jcamp_t1_1H_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5572970/jcamp_t1_1H_1D.zip)
[jcamp_t1_1H_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5572975/jcamp_t1_1H_2D.zip)

**Comment by nes-cgn** [comment]
Here the same for 13C

[jcamp_t1_13C_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5572982/jcamp_t1_13C_1D.zip)
[jcamp_t1_13C_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5572983/jcamp_t1_13C_2D.zip)

**Comment by nes-cgn** [comment]
Data for 1H T1 measurement (pseudo 2D plus delay list, as well as indiv. 1D files extracted from 2D)
[jcamp_t2_1H_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5592651/jcamp_t2_1H_1D.zip)
[jcamp_t2_1H_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592652/jcamp_t2_1H_2D.zip)
[list_t2.txt](https://github.com/cheminfo/nmr-displayer/files/5592657/list_t2.txt)

**Comment by nes-cgn** [comment]
Data for 13C T2 measurements (as for 1H), for one signal (70 ppm), plus one jcamp for pseudo 2D of entire 13C spectrum
[jcamp_t2_13C_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5592667/jcamp_t2_13C_1D.zip)
[jcamp_t2_13C_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592670/jcamp_t2_13C_2D.zip)
[jcamp_t2_13C-spec_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592671/jcamp_t2_13C-spec_2D.zip)
[list_13C_t2.txt](https://github.com/cheminfo/nmr-displayer/files/5592675/list_13C_t2.txt)

**Comment by hamed** [comment]
> @hamed could you check with @nes-cgn and add the T1 experiments in a similar way as the coffee ?
> 
> This will allow us to continue the multiple spectra analysis with a real useful case.

Sorry to interrupt the discussion, by using @hamed you are referring me, which I think is not intended.
