### ISSUE TITLE
Dataset for T2 measurement

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#686]
Could we have a dataset (many 1D NMR spectra) that would allow to make the T2 measurement ?

**Comment by nes-cgn** [comment]
13C - mostly for one signal (@70 ppm), and in file 13C-spec also for entire spectrum
[list_13C_t2.txt](https://github.com/cheminfo/nmr-displayer/files/5592682/list_13C_t2.txt)
[jcamp_t2_13C_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5592683/jcamp_t2_13C_1D.zip)
[jcamp_t2_13C_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592684/jcamp_t2_13C_2D.zip)
[jcamp_t2_13C-spec_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592685/jcamp_t2_13C-spec_2D.zip)

**Comment by nes-cgn** [comment]
For 1H (single signal)
[jcamp_t2_1H_1D.zip](https://github.com/cheminfo/nmr-displayer/files/5592688/jcamp_t2_1H_1D.zip)
[jcamp_t2_1H_2D.zip](https://github.com/cheminfo/nmr-displayer/files/5592689/jcamp_t2_1H_2D.zip)
[list_t2.txt](https://github.com/cheminfo/nmr-displayer/files/5592690/list_t2.txt)

**Comment by hamed-musallam** [comment]
@lpatiny 

it's done
