### ISSUE TITLE
Interaction of range and integral region

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#715]
If I do a ranges selection and later integrate, or if I want to work on integrals once ranges have been defined, it happens easily that if I define an integral with the same frequency range as the defined range then the range is deleted

**Comment by hamed-musallam** [comment]
@nes-cgn 
Please can you send me a short video?

**Comment by nes-cgn** [comment]
[bug_715.zip](https://github.com/cheminfo/nmr-displayer/files/5647662/bug_715.zip)
