### ISSUE TITLE
Normalize CSS

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#717]
In the example page please use modern-normalize

https://github.com/sindresorhus/modern-normalize

This will force to add the CSS that is not the same on all the browser in order to have always the same design.

For example the space around the buttons will be reset to 0 and in the nmr-displayer it should be specified.

**Comment by hamed-musallam** [comment]
@lpatiny 
I think we have to use https://github.com/infinum/emotion-normalize it's base on https://github.com/sindresorhus/modern-normalize  to integrate it with emotion js directly? what do you think?

**Comment by lpatiny** [comment]
As long as we using emotion.js it is ok indeed.
