### ISSUE TITLE
Component should not use document

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#718]
https://github.com/cheminfo/nmr-displayer/blob/34e270046447b5754f9913ecc09a531c0c7994d1/src/index.js#L17-L18

This prevents to include the component in another project and to add in the same page many copies of the component.

**Comment by lpatiny** [comment]
Event should be manage at the level of the component and not in document. You should not contaminate the DOM and this would not allow to add many instance of the nmr-displayer

**Comment by hamed-musallam** [comment]
@lpatiny 
the problem that it's a global event

**Comment by lpatiny** [comment]
Which event ?

**Comment by hamed-musallam** [comment]
like when you save a snapshot,  what happens is you press 1 and you have multiple instances?

**Comment by hamed-musallam** [comment]
i think we should pass a unique id for each instance and all the save keys in the local database should be preceded by that id

**Comment by lpatiny** [comment]
The div containing the nmr-displayer should be focussed. It is currently a problem because you have '2' in ocl-editor and for the exercises it is messy. You should not capture the numbers outside the nmr-displayer.

**Comment by hamed-musallam** [comment]
@lpatiny 
But is going to happen for preferences that we have in the browser local database.

**Comment by lpatiny** [comment]
Preferences should be the same for all the instances on nmr-displayer. It is not critical if all preferences in all the instances are not updated at the same time.
