### ISSUE TITLE
Update react-script

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#721]
Why did you downgrade react-script ?

**Comment by hamed-musallam** [comment]
@lpatiny 
because it takes a long when compile and refresh and I read about it and still a bug in the new react-script.

**Comment by targos** [comment]
I verified and the fast refresh is now good again.
There was a breaking change related to the new jsx transform in React 17. I had to make the following changes to components that use emotion:

![image](https://user-images.githubusercontent.com/2352663/101880533-5a879b80-3b93-11eb-825c-3ac3b0ebc362.png)
