### ISSUE TITLE
Exercises not working !!!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#725]
If you try to load the exercises from:

https://github.com/cheminfo/nmr-dataset2

It is not working anymore !

And in fact none of the example links from the home page of the project are working: https://github.com/cheminfo/nmr-displayer

**Comment by hamed-musallam** [comment]
@lpatiny 
Actually, it's not working anymore, I need to track the changes made by Michael.

**Comment by hamed-musallam** [comment]
we just need to change the url
