### ISSUE TITLE
Speed of selecting a spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#743]
In HSQC / HMBC example when you select a 2D spectrum it is slow.

![image](https://user-images.githubusercontent.com/1484241/101874934-104dec80-3b8a-11eb-9e0d-acd84cefa0fa.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
I think it has to be like that because once you select it many parts will refresh when it became selected.
