### ISSUE TITLE
Unselect spectrum in 2D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#746]
In 1D when you click twice on the same spectrum the first time you select it and the second time you unselected it.

The same behaviour is expected for 2D and this is not currently the case.

![image](https://user-images.githubusercontent.com/1484241/101875520-0e385d80-3b8b-11eb-96b0-a60c27fa69ec.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
this what happen the first time you select the spectrum and the second time you unselect the spectrum but it takes a while because many parts in the displayer refresh

**Comment by lpatiny** [comment]
Did you try in the HSQC / HMBC example ? Because even if I wait it does not work.

![image](https://user-images.githubusercontent.com/1484241/101896015-99741c00-3ba8-11eb-807e-fa13dd5452a4.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
I have one question, What is going to happened if you zoom in using middle mouse button to change 2d level and all the 2d unselected?

**Comment by lpatiny** [comment]
We should keep the same logic as for 1D. If I'm not wrong if nothing is selected everything scales. Same should be the case in 2D.

**Comment by hamed-musallam** [comment]
@lpatiny 
I will be terrible for 2d, when we have only one 2d spectrum selected it takes a while to zoom... the result will not be good
