### ISSUE TITLE
Drag / drop / paste molfile

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#75]
We need to add chemical structure directly in NMRDisplayer

There are 3 ways to do this:
1. Drag / drop files directly on the component (.mol extension)
2. Have a paste icon that allows to paste a molfile
3. Draw the chemical structure directly in NMRDisplayer

All the ways will call the method analysis.addMolfile(molfile);

This will append an object (or more than one for multiple fragment molecule) to the molecules array that contains various parameters. This object contains:
* molfile
* mf
* em
* mw

##  Drag / drop files

If the extension is '.mol' call the method analysis.addMolfile(). Expect that it can throw an error and display a message to the user.

## Paste a molfile

Add a paste icon in the 'Molecules' accordeon that will call analysis.addMolfile(). Expect that it can throw an error and display a message to the user.

## Draw the molecule in the browser

Add a 'add' icon in the 'Molecules' accordeon pane that will open a dialog with use the component: https://github.com/zakodium/react-ocl (and in particular react-ocl/full)

For the editor you may use the example: https://zakodium.github.io/react-ocl/?path=/story/structureeditor--from-molfile

## Improve the molecules pane to display the molecules

In the molecule pane add little tabs that allows to go from one molecule to another. I never expected more than 3 molecules but you never know ...

All the molecules are accessible using:
analysis.getMolecules();

To render the molfile use the following example:

https://zakodium.github.io/react-ocl/?path=/story/svg-renderers--molfilesvgrenderer-v2000

Under the molecule you will display:

* mf (Using our react component : https://zakodium.github.io/react-mf/?path=/story/mf--basic-rendering)
* mw: using only 2 digits (mw.toFixed(2))
* em: using 4 digits (em:toFixed(4))

In the molecules accordeon pane also add a small 'delete' icon to remove a molecule. (that will call analysis.removeMolecule(index);

**Comment by lpatiny** [comment]
Also in order to edit an existing molecule you should simply double click on it.

**Comment by nes-cgn** [comment]
Would be cool if one could zoom in/out e.g. via mousewheel. Also, adding or deleting a molecule should be smoother (so far, I need to go to the editor and delete it). In addition, dragging a molecule from another editor or or doing copy/paste instead of dragging the file would be an idea?
