### ISSUE TITLE
Disabling toolbar buttons does not work

### ISSUE THREAD

**Issue by targos** [cheminfo/nmr-displayer#753]
I'm trying to disable the import and export buttons but my config seems to have no effect (the buttons are still here in the toolbar)

![image](https://user-images.githubusercontent.com/2352663/101920470-22e91580-3bcc-11eb-81a1-0193c4b1915c.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
this issue related to Priority, the question here the priority for preferences that we store in the browser local database or for what we pass component as params?

**Comment by hamed-musallam** [comment]
@lpatiny 
how do you want me to handle it?

**Comment by lpatiny** [comment]
The priority is the props of component. If we disable some features at the level of the component those features should not appear in the local storage preferences.

For example if we disable multiple spectra analysis in the component a user should never be able to activate this feature.
