### ISSUE TITLE
nmr displayer does not open with firefox at the moment

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#755]

**Comment by hamed-musallam** [comment]
@evaziegler 
you have to provide a  screenshot from your browser console window from there we can know if the problem related to Displayer or not, What your browser version?

**Comment by evaziegler** [comment]
Hi, 
<img width="960" alt="bildschirm firefox" src="https://user-images.githubusercontent.com/60426010/102100239-7f953c00-3e29-11eb-9c44-6034027a6f52.png">
I hope this is what you need.

**Comment by lpatiny** [comment]
It is the Konsole that interests us and only when there are problems. If it works again you may explain how to you and close the ticket.

![image](https://user-images.githubusercontent.com/1484241/102102470-237fe700-3e2c-11eb-8575-77b129b0964f.png)

**Comment by evaziegler** [comment]
There is no white page yet, the displayer works. I could work with it on firefox, after I clicked  "Hilfe —> Informationen zur Fehlerbehebung —> Firefox bereinigen" on firefox (in english  "Help -> Bug fixing information (or something like that) -> Clean up Firefox").
