### ISSUE TITLE
hidding / showing panels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#756]
You can hide the panels by clicking twice on the separator.

When clicking only once (to open it again) you get a strange effect. The place for panels is there but no panels is displayed

I think we can use only one click to close / open the panels

![image](https://user-images.githubusercontent.com/1484241/102086964-26bda780-3e19-11eb-9c73-25cf689ade14.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
it must be done using double click and not single click because of drag and drop events and I can not modify the way how the slider work.....
