### ISSUE TITLE
Same problem as this morning: white page when I open the displayer with firefox

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#761]
![grafik](https://user-images.githubusercontent.com/60426010/102132884-838a8380-3e54-11eb-9f03-b131bf05cfa9.png)

**Comment by evaziegler** [comment]
![image](https://user-images.githubusercontent.com/60426010/102133544-8b96f300-3e55-11eb-9a2e-4cf19970785d.png)

**Comment by evaziegler** [comment]
I hope you can see now where the problem is.

Kind regards,
Eva

**Comment by targos** [comment]
What version of Firefox is it? I have no issues with the latest (83.0).

**Comment by evaziegler** [comment]
It´s 83.0. And I´ve got the same problem with two computers

**Comment by lpatiny** [comment]
@hamed-musallam  This problem seems to be related to localization. 

![image](https://user-images.githubusercontent.com/1484241/102197665-b9b21c80-3ec1-11eb-96e1-12426eb2cb1f.png)

**Comment by evaziegler** [comment]
Now I´ve got the same problem with the with page also on edge.

**Comment by jliermann** [comment]
I found out that the problem goes away when you delete the browser cache and re-appears after some time when a certain amount of browser cache has been accumulated. Eva tells me that it also occurrs on Edge. Could this be related to some kind of cache overflow?

**Comment by hamed-musallam** [comment]
@lpatiny 
But we do not use any kind of localization in our project

**Comment by hamed-musallam** [comment]
@targos 
what do you think? we don't use any kind of localization so maybe it's related to the browser.

**Comment by targos** [comment]
I have no idea what this could be.

**Comment by lpatiny** [comment]
@nes-cgn @jliermann do you have this problem on any other computer ? I never saw it before and nobody in the development team is able to reproduce it despite the fact we are working in a mixed environnement windows / OsX

**Comment by evaziegler** [comment]
Good morning everybody and a happy new year!

I still have the problem with the with page. Yesterday I talked with Johannes and we had the idea to make a video so you can see what I´ve done and happened. I also show you what happened with the console. I hope it can help you. 

[white page.zip](https://github.com/cheminfo/nmr-displayer/files/5774272/white.page.zip)

**Comment by hamed-musallam** [comment]
@evaziegler 
Can you send me the sample that you used so i can follow what you did.

**Comment by evaziegler** [comment]
This is the sample.
[13a_o-toluidin_95-53-4_rohdaten.zip](https://github.com/cheminfo/nmr-displayer/files/5775861/13a_o-toluidin_95-53-4_rohdaten.zip)

**Comment by jliermann** [comment]
Hi everybody, with Eva's video I was able to reproduce the problem! It seems to me it occurrs when you use automatic peak picking first and then try to pick peaks manually. Below is my console output:

![grafik](https://user-images.githubusercontent.com/40795855/103789920-d82eb200-5040-11eb-9651-f734aa4cc465.png)

**Comment by lpatiny** [comment]
I was also able to reproduce this automatic peak picking followed by manual peak picking crash.
