### ISSUE TITLE
Wrong 1D spectrum limits when uploading wobble data

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmr-displayer#763]
When you upload Bruker raw data containing wobble data from automatic tuning and matching (ATM) on ProcNo.s 700, 701 (see attached dataset), the wobble files determine the spectral limits for the 1D spectrum, leading to awkward results:

![wobble2](https://user-images.githubusercontent.com/40795855/102207667-af4a4f80-3ece-11eb-8221-7886ed90da54.png)
[beta-pinen_127-91-3.zip](https://github.com/cheminfo/nmr-displayer/files/5695368/beta-pinen_127-91-3.zip)

**Comment by jliermann** [comment]
A workaround is to delete the wobble datasets from the displayer.

**Comment by hamed-musallam** [comment]
@lpatiny 
this value comes from info.experiment

**Comment by lpatiny** [comment]
@jliermann Could you export a wobble curve as jcamp, zip it and attach it to the ticket ?

@jliermann What is expected to be the unit on the X axis for a wobble curve ?

**Comment by lpatiny** [comment]
@hamed-musallam For now please calculate the from / to (full out zoom) only based on visible spectra. We may check in the future how to make by default wobble curves invisible and @jwist is checking on how to add this annotation in the nmr-parser.

**Comment by jliermann** [comment]
@lpatiny I attached a Jcamp for the 1H wobble curve. The expected unit for x is ppm, it shows the tuning deviation of the frequency transmitter from the instrument frequency.

[beta-pinen_127-91-3_1h_wobble.zip](https://github.com/cheminfo/nmr-displayer/files/5724268/beta-pinen_127-91-3_1h_wobble.zip)

**Comment by hamed-musallam** [comment]
@lpatiny @jliermann 

I imported your sample and I don't know what is the problem
![image](https://user-images.githubusercontent.com/35760236/103768119-35673b00-5022-11eb-8f5c-2b1f3433c938.png)

**Comment by jliermann** [comment]
@hamed-musallam The problem is not importing the wobble curve itself. The problem is that if you import a dataset containing a 1D spectrum and a wobble curve, the spectral limits for the 1D will be taken from the wobble curve which makes no sense. The best thing would be to just ignore the wobble curve as it is purely technical and not relevant for spectra interpretation.

**Comment by jobo322** [comment]
Hello @hamed-musallam, when this wobb curve and a normal spectrum (e.g range in ppm 0-14) the range is calculated with the bigger range still when the wobb curve is not visible. From nmr-parser package the info.experiment is "wobble_curve". So, I think we could update the range in x for the visible data as Luc recommends.

**Comment by jliermann** [comment]
Sorry, I think I forgot that I am not only talking to NMR spectroscopists and maybe I should clarify: The wobble curve documents the quality of the transmitter's tune and match setting and is saved purely for diagnostic reasons. It is only relevant to the operator. The user recording spectra analyze molecules has no need for it so it could be disregarded during the import.

**Comment by hamed-musallam** [comment]
@lpatiny 
right now I calculate the 1d domain based on visible spectra

**Comment by hamed-musallam** [comment]
@lpatiny 
It's not a good way to change the domain every time I hide and show spectra, Do you another idea to handle this problem?

**Comment by jobo322** [comment]
@jliermann could you let me know how you generate this jcamp file. it has not the right information about the experiment
[beta-pinen_127-91-3_1h_wobble.zip](https://github.com/cheminfo/nmr-displayer/files/5830401/beta-pinen_127-91-3_1h_wobble.zip)

**Comment by jliermann** [comment]
@jobo322 I am not sure I understand the question...
This Jcamp file is a wobble curve. It reflects the transmitter adjustment of Bruker spectrometers and is saved routinely by TopSpin for diagnostic purposes. For the purely scientific user, it is meaningless and it is not a spectrum.

**Comment by jliermann** [comment]
@hamed-musallam My suggestion would be to hide or even discard wobble files by default. As I said before, these files are only important for the operator and only in case of troubleshooting.

**Comment by jobo322** [comment]
@jliermann I mean where do you obtain this jcamp file, because it has experiment as "1d" instead of "wobble_curve", I would like to know if the jcamp was generated with some code from us and fix it. 

@hamed-musallam for those cases where experiment is not correct we could looking at information for ##$SPECTYP e.g for the jcamp from @jliermann [beta-pinen_127-91-3_1h_wobble.zip](https://github.com/cheminfo/nmr-displayer/files/5858396/beta-pinen_127-91-3_1h_wobble.zip) it is <WOBBLE_CURVE>

**Comment by jobo322** [comment]
@lpatiny it is ok to ignore all wobble_curve from nmr-parser or do you prefer to ignore it just when the range of x axis is calculated if there is more than one spectrum.

**Comment by hamed-musallam** [comment]
@jliermann 
it's fixed by Alejandro by ignoring the wobble_curve spectra when load the data...

**Comment by jliermann** [comment]
For some reason, in this spectrum the wobble curve is still loaded.

[2-picolin_109-06-8_1H.zip](https://github.com/cheminfo/nmrium/files/8870358/2-picolin_109-06-8_1H.zip)

**Comment by hamed-musallam** [comment]
@jliermann 

I tested it on my local environment and it is loaded without any problem
