### ISSUE TITLE
NaN in experiment for simulated spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#772]
Please could you check why in simulated spectra the experiment is NaN ? I guess it is a problem from https://github.com/cheminfo/nmr-parser and you may have to check this with @jobo322. I think there should be at least 1D or 2D if nothing better could be determined.

![image](https://user-images.githubusercontent.com/1484241/102589632-911f6200-410f-11eb-9993-35bd95841315.png)

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 
This value comes from info. experiment so it should be handled from mr-parser.

**Comment by jobo322** [comment]
@lpatiny, I assume that it is a jcamp. do you put any metadata there? I mean something to determine the dimension of the spectrum.

**Comment by lpatiny** [comment]
@jobo322 Here is the file: https://raw.githubusercontent.com/cheminfo/nmr-displayer/master/public/data/tests/simulated/d1-1.2_j7.jdx

I guess you should be able to find out that the experiment is 1d (fall back ?)
