### ISSUE TITLE
Color picker and mouse out

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#773]
It it not very intuitive that the color picker close if the mouse is outside the color selection dialog.

If would be better if you need to click outside the dialog to close it.

One way is to create an invisible div that is between the color dialog and the rest of the application and that catch the event.

**Comment by hamed-musallam** [comment]
@lpatiny 
I think it is better if add a close button on the left top side of the color picker modal? What do you think?

**Comment by lpatiny** [comment]
Both can coexist. Click on a close button or click outside. The normal behaviour of a `<input type="color">` is to allow a click outside.
