### ISSUE TITLE
Changing the preferences in peaks does not work

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#782]
Even if I change the column to display it is always the same columns that are displayed

![image](https://user-images.githubusercontent.com/1484241/103662548-5ff8bb80-4f70-11eb-8503-0ed91dd2161b.png)

**Comment by lpatiny** [comment]
Could be related to this error that yields to a blank screen on my browser:

![image](https://user-images.githubusercontent.com/1484241/103663115-093fb180-4f71-11eb-8a4a-2b94dcd7537b.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
i fixed it but you have to clear the local storage first .

**Comment by lpatiny** [comment]
You need to keep track of a version of localStorage and clear it automatically if there is a change of version.
We can not ask the end users to clear their local storage
