### ISSUE TITLE
ranges picking crashes for 1H jcamp.dx files (dataset1)

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#786]
For a couple of 1H spectra (light version, jcamp.dx), the automatic ranges picking leads to a crash. So far, I have seen this for the files from nmr-dataset1 (CAS) no.'s 57946-61-9, 492-62-6, 2216-51-5 (and sure there are more). The following error is displayed:

TypeError: a.j[o] is undefined

$o@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:129430
g
c</<@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:3509
ac@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:134752
g
227/ic<@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:136253
t@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:123367
svg
rc@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:136438
div
La@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:72389
div
Pa@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:69663
Vc@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:149690
div
e@https://cheminfo.github.io/nmr-displayer/static/js/0.e79ea711.chunk.js:2:3183976
div
e@https://cheminfo.github.io/nmr-displayer/static/js/0.e79ea711.chunk.js:2:3185901
div
c</<@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:3509
ed@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:226943
div
div
as@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:181482
div
c</<@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:3509
Bo@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:126099
d@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:1249
Ti@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:79333
ts@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:178257
227/xc<@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:139021
n@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:177590
227/tj<@https://cheminfo.github.io/nmr-displayer/static/js/1.90c73458.chunk.js:1:446643
div
div
l@https://cheminfo.github.io/nmr-displayer/static/js/10.49485816.chunk.js:1:676
G@https://cheminfo.github.io/nmr-displayer/static/js/main.f7262023.chunk.js:1:5565
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:7001
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:7952
Suspense
div
c</<@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:3509
div
Y@https://cheminfo.github.io/nmr-displayer/static/js/main.f7262023.chunk.js:1:5741
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:5055
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:6037
ce@https://cheminfo.github.io/nmr-displayer/static/js/main.f7262023.chunk.js:1:8932
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:7001
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:7952
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:5055
t@https://cheminfo.github.io/nmr-displayer/static/js/4.d1e7cdbf.chunk.js:2:23786

**Comment by hamed-musallam** [comment]
@lpatiny 
Can you please test it from your side because I can't reproduce this problem?

**Comment by hamed-musallam** [comment]
@lpatiny 
Can you please test it from your side because I can't reproduce this problem?

**Comment by lpatiny** [comment]
I can not reproduce this problem neither. Does it crash systematically for you @nes-cgn ? Can you make a video with the full process ?
How do you load the spectrum ? A drag and drop on the nmr-displayer ?

**Comment by nes-cgn** [comment]
I tried it again, and now, there is no more problem. Issue can be closed from my side
