### ISSUE TITLE
Multiple reference does not take into account nbPeaks

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#794]
![image](https://user-images.githubusercontent.com/1484241/104333935-0fdea380-54f2-11eb-9e66-4f39fe8e6662.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
i tracked what i pass to your function and this what I found 
{targetX: 0, from: 2.4658087130369726, to: 5.152177225911352, nbPeaks: 2}

so I think the problem related to xyXShift function, Can you check it.
