### ISSUE TITLE
Can not set from / to in calibration from SHIFT + drag

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#802]
Seems the shift + define zone does not work anymore

![image](https://user-images.githubusercontent.com/1484241/104694243-34619800-570b-11eb-8ee6-fd6cce01d867.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
actually, it's work with me !!!!!!!!! can you test it again

**Comment by lpatiny** [comment]
Ok the problem was that I didn't select the right tool to draw the range.

Please when we open this dialog change automatically the tool
