### ISSUE TITLE
Strange behaviour if after FT and FID present

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#804]
One on 2 labels should not be present I think

![image](https://user-images.githubusercontent.com/1484241/104694928-38da8080-570c-11eb-9b1c-867add815ef9.png)

You can drag / drop the attached zip file

[BariatricRats.zip](https://github.com/cheminfo/nmr-displayer/files/5819036/BariatricRats.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 
i did not  get what you mean, when I import the zip file  I get Fid and FT  for every spectra, by default we displayer FT spectra if nothing is selected and if you select one we look if it's FT we display the all visible FT and the same for FID

**Comment by lpatiny** [comment]
The values should not be displayed if the spectra are not visible

![image](https://user-images.githubusercontent.com/1484241/104748466-123f3880-5752-11eb-8163-ffa3922a9cc6.png)

In this case we have FIT and after FT and I think that the values are shown for all the spectra and not only the visible ones.
