### ISSUE TITLE
Cannot edit nmrium file after saving

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#809]
With the attached package, I cannot change the ranges for 1H - if I try to, the displayer crashes.
[issue_810.zip](https://github.com/cheminfo/nmr-displayer/files/5819310/issue_810.zip)

**Comment by nes-cgn** [comment]
In the zip file, there is the nmrium, plus all individual spectra files

**Comment by hamed-musallam** [comment]
@nes-cgn 
Can you export it another time and remove ranges or peaks or whatever you need from these parameters and check if you have this error again.

It's important to notice that some parameters must not be removed from the json

**Comment by nes-cgn** [comment]
Thank you. Yes, it works now. But there is still an issue with the  
assignment (interactive frequency-atom-table connection) as explained  
in issue #810

Quoting hamed-musallam <notifications@github.com>:

> @nes-cgn
> Can you export it another time and remove ranges or peaks or  
> whatever you need from these parameters and check if you have this  
> error again.
>
> It's important to notice that some parameters must not be removed  
> from the json
