### ISSUE TITLE
assignment not saved after modifying nmrium file

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#810]
First, I would like to state that the nmrium file is really a very important advantage of the displayer. It really helps and is very convenient. However, related to issue #809, if I do the assignment or modify it after having stored the nmrium file, it seems, that the connections between atoms and frequencies are there (i.e. hovering over signals or table entries is interactive), but the yellow circles at the assigned atoms do not highlight any more.

**Comment by hamed-musallam** [comment]
@nes-cgn 
I will check it with Michael? To know exactly what I have to do
