### ISSUE TITLE
Values not shown

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#826]
Hello,

if you click "automatic peak picking" I can´t see the values in the list "peaks". 

![grafik](https://user-images.githubusercontent.com/60426010/105025286-6cd7dd80-5a4d-11eb-9896-6305cae0e708.png)

Kind regards, Eva

**Comment by hamed-musallam** [comment]
@evaziegler 
you just need to clear the local storage of the browser , or change the preferences from the same panel in the top right side you have Gear icon click on it and then change table columns preferences.
