### ISSUE TITLE
calculation of 13c projection returns scaled 1D projection

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#827]
For some cases, the calculation of projections for the 2D returns a scaled projection (compressed in dimension). See screenshots. I will provide the spectra in a moment
![projection_13c_hmbc](https://user-images.githubusercontent.com/47237343/105034968-964b3600-5a5a-11eb-97d6-713eeb57094e.PNG)
![projection_13c_hmbc_2](https://user-images.githubusercontent.com/47237343/105034975-96e3cc80-5a5a-11eb-88da-0f9e93d47fcf.PNG)

it does not happen always
![projection_13c_hmbc_OK](https://user-images.githubusercontent.com/47237343/105035016-a6fbac00-5a5a-11eb-8098-0599731a0851.PNG)

**Comment by hamed-musallam** [comment]
@nes-cgn 
Can you send me a sample to test this case from my side?

**Comment by nes-cgn** [comment]
[failing-example.zip](https://github.com/cheminfo/nmr-displayer/files/5835941/failing-example.zip)
[working-example.zip](https://github.com/cheminfo/nmr-displayer/files/5835943/working-example.zip)

These zip folders contain each an "nmrium" file (JSON) produced from a set of experiments. If it is more convenient, I can send you individual hmbc files, too.

**Comment by hamed-musallam** [comment]
@nes-cgn 
Can you please test it again?

**Comment by hamed-musallam** [comment]
@nes-cgn 
Can you please check this again and close the issue if it is ok?
