### ISSUE TITLE
2D spectra no longer visible after switching one of them off

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#828]
When looking at a HSQC and HMBC and then unmarking one of them selectively (using the "eye icon"), all of them disappear and cannot be retrieved again (only by loading set of experiments anew). See movie (happened to me on several occasions)

https://user-images.githubusercontent.com/47237343/105040843-a0713280-5a62-11eb-9d5b-985a1f95c86d.mp4

**Comment by hamed-musallam** [comment]
@nes-cgn 
Can you test it again, we solve it yesterday when we solved another issue similar to this.
