### ISSUE TITLE
wrong scaling of 2D experiments' spectral width

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#829]
For several examples, I found that the spectral width (displayed frequency range) for 2D experiments is now wrongly displayed. Some recent examples are displayed below (these are mostly 19F-1H experiments or vice versa, but it also happened with a plain H-H cosy to me)

![COSY](https://user-images.githubusercontent.com/47237343/105136314-bb3eb800-5af1-11eb-8520-342d155c18df.PNG)
![COSY-should-be](https://user-images.githubusercontent.com/47237343/105136317-bbd74e80-5af1-11eb-8f23-bc0364e6395f.PNG)
![F-H-COSY](https://user-images.githubusercontent.com/47237343/105136318-bbd74e80-5af1-11eb-8671-64d864e13e1b.PNG)
![F-H-COSY-should-be](https://user-images.githubusercontent.com/47237343/105136320-bc6fe500-5af1-11eb-9f71-f436ae8cb3a3.PNG)
![H-F-HOESY](https://user-images.githubusercontent.com/47237343/105136321-bc6fe500-5af1-11eb-9c10-420a4e42da2c.PNG)
![H-F-HOESY-should-be](https://user-images.githubusercontent.com/47237343/105136322-bd087b80-5af1-11eb-88f2-eab8493f1dcb.PNG)

**Comment by nes-cgn** [comment]
Example files with the problem
[K42.zip](https://github.com/cheminfo/nmr-displayer/files/5840540/K42.zip)

**Comment by nes-cgn** [comment]
Another remark - if I use the "release" on nmrium.org, it does not happen

**Comment by hamed-musallam** [comment]
@nes-cgn @lpatiny 
Can you check if the bug disappear?
