### ISSUE TITLE
Switching between tabs reset zoom

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#834]
It is quite annoying that when you switch of tabs we reset the from / to and I was thinking about the more intuitive behaviour. What is sure is that resetting is not intuitive.

For now I would keep the same from / to as when we left the tab so that going back to the tab we see the same zoom level.

**Comment by hamed-musallam** [comment]
@lpatiny 
Actually, we change the domain every time we switch between tabs (Nucleus) because we have different spectra, What you request to save the zoon level when switching between tabs?
