### ISSUE TITLE
Example 1H / 15N is broken

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#835]
![image](https://user-images.githubusercontent.com/1484241/105209111-c0c7ec80-5b49-11eb-9a38-42a71aa5b576.png)

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 
this example added by Michale in this ticket 
https://github.com/cheminfo/nmr-displayer/issues/779
and I informed you that z array returns empty....

**Comment by lpatiny** [comment]
Duplicate of https://github.com/cheminfo/nmr-displayer/issues/779
