### ISSUE TITLE
Do not use arrow functions for React Components

### ISSUE THREAD

**Issue by targos** [cheminfo/nmr-displayer#838]
See https://github.com/cheminfo/nmr-displayer/commit/86aace4a9ebb3ed9fec5e4f8ce6cef46740cf32e

If an anonymous function is used, the React profiler and stack traces are not very helpful because they show a lot of "Anonymous" lines.

Before: 
![image](https://user-images.githubusercontent.com/2352663/105477871-bff69e00-5ca2-11eb-9381-b0808b19a35b.png)

After:
![image](https://user-images.githubusercontent.com/2352663/105477900-ca189c80-5ca2-11eb-9bcf-3efaf1969a78.png)

**Comment by hamed-musallam** [comment]
@targos 
Actually, I do not use any anonymous function it is even prevented from eslint rules

**Comment by hamed-musallam** [comment]
@targos 
Maybe because I use curry function in some places???

**Comment by targos** [comment]
Look at the commit I did: https://github.com/cheminfo/nmr-displayer/commit/86aace4a9ebb3ed9fec5e4f8ce6cef46740cf32e

I wrote "anonymous" because arrow functions are anonymous

**Comment by hamed-musallam** [comment]
@targos 
ok I will change all the component
