### ISSUE TITLE
Remove mutation of global state in reducers

### ISSUE THREAD

**Issue by targos** [cheminfo/nmr-displayer#839]
It is strictly forbidden to do any mutation of "global" variables (meaning doing side-effects) during the execution of a reducer.

![image](https://user-images.githubusercontent.com/2352663/105485115-ae19f880-5cac-11eb-8f6a-213d91200bed.png)

Examples:

- Here, `initZoom1DHander` modifies the `spectraZoomHandlers` object, which is an external variable.
https://github.com/cheminfo/nmr-displayer/blob/a94e3a25ed659366bbd469ed7e4c572aa519d693/src/component/reducer/actions/Zoom.js#L18-L18
https://github.com/cheminfo/nmr-displayer/blob/e853415e293a979df635d59141072ad92add0117/src/component/reducer/actions/LoadActions.js#L31-L31

- Here, `initiateObject` replaces the value of `AnalysisObj`, which is also an external variable.
https://github.com/cheminfo/nmr-displayer/blob/1dced61182b112e52470741c0956cbbc5d66c564/src/component/reducer/core/Analysis.js#L1-L10
https://github.com/cheminfo/nmr-displayer/blob/e853415e293a979df635d59141072ad92add0117/src/component/reducer/actions/LoadActions.js#L19-L19

Those objects should be part of the state.

**Comment by hamed-musallam** [comment]
Spectrum1DZoomHelper class because it's helper class no need to be in the state because it handles things and then the result that we git effect the state..

What to do in this case, can we use current() or original function from immer

**Comment by hamed-musallam** [comment]
@targos 
is there any way to not set AnalysisObj inside the state???
