### ISSUE TITLE
Experiments information for 1D experiments is "NaN"

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmr-displayer#846]
@jobo @lpatiny The info.experiment property within 1D experiments is gone. That value is currently "NaN" instead of "1d", "dept" etc. 
Probably it's since the most recent nmr-parser version?  

For 2D experiments it is still working.

![picture](https://user-images.githubusercontent.com/30418272/106049393-5af9d880-60e6-11eb-9376-324081d372eb.png)

**Comment by hamed-musallam** [comment]
@jobo322 
info.experiment return always NaN, I think because it returns like that from the nmr-parser?
