### ISSUE TITLE
contour plot calculation optimization: only 2 components (positive / negative)

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#857]
I think that we don't need to create a component for each contour line but we can create one path for positive and one path for negative. So the path would look like 'M .. L. L. L. L M .. L. L. L. ..... z'

This could improve the speed

**Comment by hamed-musallam** [comment]
@lpatiny 

check it please at contours-single-path branch

**Comment by hamed-musallam** [comment]
@lpatiny 

Also, i use for loop - cash length and it is faster than reduce so maybe we have to move to use for loop - cash length instead of reduce function
