### ISSUE TITLE
Performance check of loading spectra is impossible

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#859]
When we load spectra like COSY ethylbenzene with Performance recording the result contains mainly anonymous function that prevents to find the limiting steps

![image](https://user-images.githubusercontent.com/1484241/109182279-1b79e700-778d-11eb-9aef-95ce9afb54c0.png)

@targos Any idea what could be the reason ?

**Comment by targos** [comment]
is it with the production build?

**Comment by lpatiny** [comment]
No it is in development mode using `npm start`

https://github.com/cheminfo/nmr-displayer/blob/5b5ac2b8a88f5793a49704daded2eca6a0b7dd9f/package.json#L24-L25

**Comment by targos** [comment]
The anonymous functions are not from our code (here it's in immer)
