### ISSUE TITLE
Move samples.json to data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#873]
By default the nmr-displayer should load 'empty.json'.

samples.json should be published on gh-pages and we will change the link on the homepage to load this file.

Those 2 lines will therefore become obsolete:

https://github.com/cheminfo/nmr-displayer/blob/76278b4319c56c740baf42d31871cfdb832bf236/.github/workflows/publish.yml#L22-L24

**Comment by hamed-musallam** [comment]
@lpatiny 
you did it as I remember so what you need me to do?
