### ISSUE TITLE
Saving / reloading nmrium file

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#874]
If you save and reload a nmrium file
[test (1).nmrium.zip](https://github.com/cheminfo/nmr-displayer/files/6099506/test.1.nmrium.zip) the spectrum is centered instead of the bottom of the screen.

![image](https://user-images.githubusercontent.com/1484241/110286313-01d66c00-7fe5-11eb-8dc1-8617c266bd67.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
![image](https://user-images.githubusercontent.com/35760236/110311608-53daba00-8004-11eb-9c45-73aec6351951.png)

the problem is related to spectrum data because the data show that isFid and i know it's not but the data the store say that.

**Comment by lpatiny** [comment]
I guess you change this property making the FT and you need to keep the original value somewhere to store in the nmrium file.

**Comment by hamed-musallam** [comment]
@lpatiny actually i keep the original info, you can test the 1h example

**Comment by lpatiny** [comment]
It is not the original data that is saved but the one after FT. This is not correct.
In the nmrium file only original data should be saved.

**Comment by hamed-musallam** [comment]
@lpatiny 
you have first to export the file  another time before test if it fixed or not.
