### ISSUE TITLE
No summary for this example

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#881]
After range picking of 1D and zone picking of 2D there is no summary displayed.

[106-89-8.zip](https://github.com/cheminfo/nmr-displayer/files/6102098/106-89-8.zip)

![image](https://user-images.githubusercontent.com/1484241/110336666-5dc0e500-8025-11eb-9dd2-d5ad2ada4857.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
Fixed by Michael, Can you test it?
