### ISSUE TITLE
Drag / drop of FID does not center the spectrum by default

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#888]
If we have only FIDs they should be displayed centered

[13C_Cytisin_600_fid.dx.zip](https://github.com/cheminfo/nmr-displayer/files/6117352/13C_Cytisin_600_fid.dx.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 
I dragged and drop your file into a blank screen and it works like what you purpose.
