### ISSUE TITLE
Allow to delete a peak like for ranges or integrals

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#895]
When hover a peak a little 'delete' icon should also appear

![image](https://user-images.githubusercontent.com/1484241/110775310-13c34380-825f-11eb-915c-04c38c89b582.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

your request is to remove the delete button in the previous ticket,

https://github.com/cheminfo/nmr-displayer/issues/749

**Comment by lpatiny** [comment]
Yes we should just allow 'backspace' or 'delete' when over to remote this annotation.
