### ISSUE TITLE
Add delete icon on range hover

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#899]
Also add the possibility when hovering a range to delete this specific range

![image](https://user-images.githubusercontent.com/1484241/110783482-ce0b7880-8268-11eb-950d-e2c9aca84004.png)

**Comment by hamed-musallam** [comment]
@lpatiny

your request is to remove the delete button in the previous ticket,

#749

**Comment by lpatiny** [comment]
Ok...

The problem is to be consistant between all the annotations:
- integrals
-  ranges
- peak picking
- zones

Currently integrals and zones have the '-' icon.

Currently ranges allow 'backspace' to delete it.

I think in all the cases 'backspace' (or delete) should work with integrals, ranges, zones and peaks.

We can remove the '-' icon from integral and zones as well then.
