### ISSUE TITLE
Using await rather than 'then'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#906]
I often see in the code the use of then rather than await

https://github.com/cheminfo/nmr-displayer/blob/f6f30e9e12256c2b0c54ed69da5f87084294613f/src/component/reducer/Reducer.ts#L160-L167

I really prefer to have the 
```js
const data = await SpectraManager.addBruker( 
   { display: { name: zipFile.name } }, 
   zipFile.binary, 
 )
 action.payload = data; 
 dispatch(action); 
```
The code is shorter and easier to read. 

@hamed-musallam  Why not using this ?
@targos What do you think ?

**Comment by targos** [comment]
because `dispatch` and `dispatchMiddleware` are synchronous. You have to use .then when you manipulate promises in synchronous functions.
