### ISSUE TITLE
Joining experiments in summary ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#917]
If you take cytisine example and make the zone peaking on HSQC and HMBC the summary table becomes quite big

Home HSQC / HMBC are joined ? On the top of the columns you have the list of protons but it does not seem that if you have the same proton in HSQC and in HMBC they are in the same column. I would expect this. So in the header of the table I would only display the proton number (and not HSQC / HMBC) and in the cells of the table I would have 2 (or more) different code to highlight the fact that the correlation is visible in HSQC and HMBC.

@michaelwenk What do you think ?

![image](https://user-images.githubusercontent.com/1484241/111588686-2e983980-87c4-11eb-879c-737cbfb3f396.png)

**Comment by michaelwenk** [comment]
@lpatiny The signal grouping across all given spectra is done by chemical shift matching. If you increase the shift tolerance for H in the tolerance modal then the number of columns is reduce, depending on which new groups have been found.

One potential problem with this approach could be if the spectra are not aligned properly (shifts in chemical shifts).  Then one needs to increase the tolerances even more, but maybe with wrong grouping then, or a kind of correction for that issue.  

Regarding the labels of HSQC, HMBC etc. we could remove that first column and the information in the headers on right table part and replace it by an information when hovering over the first cells left table part/column headers.

**Comment by lpatiny** [comment]
Ok so the problem is the result of peak picking in this case that is not precise enough and does not find aligned peaks.

If HSQC and HMBC are correctly aligned can we distinguish in the table the correlation found in one spectrum or the other ?
