### ISSUE TITLE
No way to add molecule in fullscreen mode

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#96]

**Comment by hamed-musallam** [comment]
actually I need a suggestion, because when we put it in full-screen nothing like popup can show above it.
when I inspect element for the popup element that I used from material UI I found that it's added at the root element of the page.

**Comment by lpatiny** [comment]
Soon or later we will have to get rid of material-ui so don't use it too much and create a DIV yourself that you could place where you want in the DOM.
