### ISSUE TITLE
Save data in JSON

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#97]
When drag / drop a jcamp we should save the data not in original but directly in `data`

```js
{
  "data1d": [
    {
      "data": {},
      "id": "0abwvynpah97",
      "source": {
        "jcamp": null,
        "jcampURL": null,
        "original": {
          "x": [
            0.5914089613428362,
            0.5915260807910494,

```

**Comment by hamed-musallam** [comment]
@lpatiny 
but put in your concerns that we use data for the last status of it after we apply filters, you aware of this?

**Comment by lpatiny** [comment]
You are right, thanks for reminding me this !
